### ISSUE TITLE
[BUG]开启得pac，很多流量走了全局，测试，访问淘宝，出现是境外得，看虎牙卡的要死，应该是bug

### ISSUE THREAD

**Issue by cjsvaxlp** [HMBSbige/ShadowsocksR-Windows#100]
**描述 bug**

简要描述所遇到的bug

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 
2. 
3. 

**预期行为**

简要描述进行以上操作后预期的脚本行为

**截图**

如果可以，请添加屏幕截图以帮助解释您的问题

**环境**

 - 系统：[如 Windows 10 1809]
 - 浏览器：[如 Chrome 74.0.3729.157，无关则删除]
 - 程序版本：[如 5.0.0.0 .Net Core SelfContained x64]
 
**其它内容**

在此添加有关此问题的任何其它内容。
最好能贴上相关的日志

**Comment by HMBSbige** [comment]
自己的问题，请自查

**Comment by haley924** [comment]
刚更新版本，也发现卡顿问题，进TWITCH首页，页面还读取错误，看油管有不知名的卡顿和断流，于是老实的退回了上个版本，所有问题就没了

**Comment by HMBSbige** [comment]
@haley924 改个 UI 也能改成断流？

真有bug就详细描述，或者提交日志，一上来就批判一番，谁知道什么问题

看你们描述只能看出 小白不懂设置/自己节点有问题
