### ISSUE TITLE
[BUG]win10专业版 1809   锁定计算机后 再解锁 会多出 好多  pacjsworker.exe

### ISSUE THREAD

**Issue by lgq0416** [HMBSbige/ShadowsocksR-Windows#101]
**描述 bug**
win10专业版 1809   锁定计算机后 再解锁 会多出 好多  pacjsworker.exe
简要描述所遇到的bug
进程描述  HTTP Auto Proxy Detection Worker Process    占用N多内存
**如何复现**
锁定计算机后 再 解锁

**

**截图**

![q1111](https://user-images.githubusercontent.com/55870009/66692907-8da37600-ecd5-11e9-8e45-6c924ea483c7.jpg)

**环境**

 - 系统：Windows 10 1809

 - 程序版本：v5.1.3.4  ShadowsocksR-netcore-win64.zip

**Comment by HMBSbige** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows/issues/8#issuecomment-489397756
