### ISSUE TITLE
期待能添加延迟测试功能，或者能自动显示延迟。 这样的话，方便选用节点。

### ISSUE THREAD

**Issue by yang12me** [HMBSbige/ShadowsocksR-Windows#102]
**您的功能请求是否与 BUG 有关？ 请描述一下。**

简明扼要地描述了问题所在

**描述您想要的解决方案**

简明扼要地描述您想要发生的事情

**描述您考虑过的替代方案**

对您考虑的任何替代解决方案或功能的简明扼要描述

**其它内容**

在此处添加有关功能请求的任何其它内容或屏幕截图

**Comment by HMBSbige** [comment]
#81

**Comment by 108678868** [comment]
这个功能应该是刚需
