### ISSUE TITLE
感觉左键托盘图标的功能可以换一个

### ISSUE THREAD

**Issue by IptablesNat** [HMBSbige/ShadowsocksR-Windows#105]
每次点击托盘图标都是想去看“服务器连接统计”，然后调整节点开关，，而不是去“编辑服务器”。。。

可以搞个小调查，看看支持左键“服务器连接统计”的多，还是左键“编辑服务器”的多（现有模式）。。

**Comment by anticpc** [comment]
> 每次点击托盘图标都是想去看“服务器连接统计”，然后调整节点开关，，而不是去“编辑服务器”。。。
> 
> 可以搞个小调查，看看支持左键“服务器连接统计”的多，还是左键“编辑服务器”的多（现有模式）。。

ctrl+左键

**Comment by IptablesNat** [comment]
> > 每次点击托盘图标都是想去看“服务器连接统计”，然后调整节点开关，，而不是去“编辑服务器”。。。
> > 可以搞个小调查，看看支持左键“服务器连接统计”的多，还是左键“编辑服务器”的多（现有模式）。。
> 
> ctrl+左键

谢谢提醒，，，是新版有的，还是一直就有的？

**Comment by 108678868** [comment]
在小飞机图标上点中键就可以

**Comment by anticpc** [comment]
> > > 每次点击托盘图标都是想去看“服务器连接统计”，然后调整节点开关，，而不是去“编辑服务器”。。。
> > > 可以搞个小调查，看看支持左键“服务器连接统计”的多，还是左键“编辑服务器”的多（现有模式）。。
> > 
> > 
> > ctrl+左键
> 
> 谢谢提醒，，，是新版有的，还是一直就有的？

一直都有。

单独鼠标操作：
鼠标左键单击/双击 托盘图标后，会弹出 编辑服务器 窗口。
鼠标中键单击 托盘图标后，会弹出 服务器连接统计 窗口。
鼠标右键单击 托盘图标后，会弹出 托盘菜单(~~~)。

键盘+鼠标操作
按下 Shift键，然后鼠标左键单击 托盘图标后，会弹出 选项设置 窗口。
按下 Ctrl键，然后鼠标左键单击 托盘图标后，会弹出 服务器连接统计 窗口。
按下 Alt键，然后鼠标左键单击 托盘图标后，会弹出 端口设置 窗口。

**Comment by shanefengcn** [comment]
可否设置一个选项让大家自己选？

**Comment by HMBSbige** [comment]
@shanefengcn 世界加钱可及

**Comment by shanefengcn** [comment]
> @shanefengcn 世界加钱可及

来来来 来谈个价格吧hhh

**Comment by HMBSbige** [comment]
@shanefengcn 便宜点就 10000 吧
