### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by negnegneg** [HMBSbige/ShadowsocksR-Windows#109]
1、建议作者弄一个选择服务器的快捷键，现在换服务器节点需要三四步才能搞定，有点不方便。

2、如果作者有时间和想法，我建议作者给这个软件换个皮，类似clash for windows那样，确实是被界面的精美吸引到了，这个新的版本可以收费。

**Comment by HMBSbige** [comment]
@negnegneg 选择服务器不挺方便的吗，直接在服务器记录窗口选不就行了，还能怎么快捷键啊？

**Comment by negnegneg** [comment]
才发现可以这样选择服务器节点，抱歉抱歉。

**Comment by anticpc** [comment]
> 才发现可以这样选择服务器节点，抱歉抱歉。

#78
