### ISSUE TITLE
建议发布包带上版本号

### ISSUE THREAD

**Issue by lyafancn** [HMBSbige/ShadowsocksR-Windows#111]
如题

**Comment by HMBSbige** [comment]
在？有人 PR 吗

改个publish[脚本](https://github.com/HMBSbige/ShadowsocksR-Windows/blob/master/publish.cmd)而已

**Comment by oToToT** [comment]
我來看個

**Comment by HMBSbige** [comment]
> 我來看個
> @HMBSbige 這個要做自動判斷版本號的嗎?
> 還是就跟 [UpdateChecker.cs](https://github.com/HMBSbige/ShadowsocksR-Windows/blob/master/shadowsocks-csharp/Controller/HttpRequest/UpdateChecker.cs) [](/HMBSbige/ShadowsocksR-Windows/blob/HEAD@{2019-10-21T14:21:30Z}/shadowsocks-csharp/Controller/HttpRequest/UpdateChecker.cs) 一樣用手填即可呢?

读取 UpdateChecker 里的版本号，自动填文件名吧
