### ISSUE TITLE
使用订阅后生成的gui-config.json可否在每个节点前加入"remarks" : "xxxxxxxxxxxx"（节点名字）

### ISSUE THREAD

**Issue by tingswin** [HMBSbige/ShadowsocksR-Windows#113]
使用订阅后生成的gui-config.json可否在每个节点前加入"remarks" : "xxxxxxxxxxxx"（节点名字）
不然分不清节点备注名是哪个
"remarks" : "xxxxxxxxxxxx"，
"Id":"xxxxxxxxxxxxx",
"server":"xxxxxxxxxxx",
"Server_Port":xxxxxxxxxx,
"Server_Udp_Port":xxxxxxxx,
"Password":"xxxxxxxxxxx",
"Method":"aes-256-cfb",
"Protocol":"auth_aes128_sha1",
"ProtocolParam":"xxxxxxxxxx",
"obfs":"http_simple",
"ObfsParam":"xxxxxxxxx",
"Group":"xxxxxxxxx",
"SubTag":"xxxxxxxxxx",
"Remarks_Base64":"xxxxxxxxxxxxx",
"Enable":true,
"UdpOverTcp":false

**Comment by HMBSbige** [comment]
不是有的吗？Remarks_Base64

**Comment by tingswin** [comment]
> 不是有的吗？Remarks_Base64

需要对Remarks_Base64解码，看起来不直观哎

**Comment by HMBSbige** [comment]
@tingswin 所以为什么要在配置文件看？配置文件又不是给用户看的。我是懒得改了，欢迎PR

**Comment by tingswin** [comment]
> @tingswin 所以为什么要在配置文件看？配置文件又不是给用户看的。我是懒得改了，欢迎PR

有个逗比超级Ping的小工具可以批量ping节点 ，通过读取gui-config.json中的Remarks来显示备注。
![image](https://user-images.githubusercontent.com/33353115/67268745-d59d7680-f4e7-11e9-8e49-2e4531e07639.png)

**Comment by HMBSbige** [comment]
这种 Issue 就很奇怪，为什么不让别的软件来兼容呢？？？

**Comment by tingswin** [comment]
> 这种 Issue 就很奇怪，为什么不让别的软件来兼容呢？？？

最重要的原因是这软件的开发者被抓了，开发者是逗比根据地（doubi）。。。。。。
好像除了这个，现在也没有可以批量读取gui-config.json节点的软件了

**Comment by tingswin** [comment]
> 这种 Issue 就很奇怪，为什么不让别的软件来兼容呢？？？

remarks在原版ssr上是有的，逗比应该是根据这个来写的这个程序

**Comment by ZLplLQc** [comment]
（临时解决办法）将下面这些代码保存为tool.html然后拖进浏览器里面。
```html
<html>

<head>
    <title>ssr添加remarks</title>
</head>

<body>
    选择gui-config.json处理完成后默认下载目录将多出个remarks.json<br />
    <input type="file" onchange="ReadFile();" id="FileInput" accept=".json">
</body>
<script>

    function download(filename, text) {
        var element = document.createElement('a');
        element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
        element.setAttribute('download', filename);
        element.style.display = 'none';
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    }

    function ReadFile() {
        var file = document.getElementById("FileInput").files[0];
        var reader = new FileReader();
        reader.onload = function (e) {
            var json = JSON.parse(e.target.result);
            json["configs"].forEach(el => {
                el["remarks"] = decodeURIComponent(escape(window.atob(el["Remarks_Base64"])));
            });
            download("remarks.json", JSON.stringify(json, null, 4));
            alert("新文件已经保存到默认下载目录中");
        };
        reader.readAsText(file);
    }

</script>

</html>
```
