### ISSUE TITLE
新panel设计，包括节点延迟，实时速度，快速修改本地端口

### ISSUE THREAD

**Issue by 00a7a00** [HMBSbige/ShadowsocksR-Windows#118]
**您的功能请求是否与 BUG 有关？ 请描述一下。**

与BUG无关

**描述您想要的解决方案**

新panel设计，包括节点延迟，实时速度，快速修改本地端口

**描述您考虑过的替代方案**

没有考虑过

**其它内容**

https://github.com/00a7a00/shadowsocksr-csharp
有截图及代码，有点垃圾但是能用，仅供参考
PS：登录功能不兼容市面上的panel

**Comment by HMBSbige** [comment]
@00a7a00 加钱什么都有，欢迎机场主来定制
