### ISSUE TITLE
4.9.4无配置启动失败

### ISSUE THREAD

**Issue by wxlg1117** [HMBSbige/ShadowsocksR-Windows#12]
从你的releases下的,
![Snipaste_2019-05-10_10-46-39](https://user-images.githubusercontent.com/9752596/57499369-0b6fe980-7312-11e9-9e61-106f11319c6e.png)

我自己更新了你的代码编译的debug版本:
![Snipaste_2019-05-10_10-45-49](https://user-images.githubusercontent.com/9752596/57499399-204c7d00-7312-11e9-8532-3db7a0dcb2f3.png)

如果是界面更新4.9.4版本或者releases下载来覆盖了老版本,启动的时候载入了原来的配置,那启动就没问题,
应该还是那个气泡显示当服务器备注为空的代码那块问题;

PS:另外给大佬这么勤劳白天黑夜的更新修复代码点个赞.

**Comment by wxlg1117** [comment]
大神看看能不能显示当前服务器名称那一块代码从原来的显示"备注" 改成显示"群组名+备注"啊?

**Comment by HMBSbige** [comment]
是指通知栏图标标题第二行那改成 `群组名:备注` 吗

**Comment by wxlg1117** [comment]
对呀对呀,因为一般用这个比较多的人都会多个地区的多组服务器,那个分组还是挺好用的
