### ISSUE TITLE
When I choose Proxy setting->Proxy rule->Bypass LAN && China I can not open Twitter websites.

### ISSUE THREAD

**Issue by MagicalWong** [HMBSbige/ShadowsocksR-Windows#122]
When I choose Proxy setting->Proxy rule->Bypass LAN && China I can not open Twitter websites.

**Comment by HMBSbige** [comment]
@MagicalWong Please use pure dns when you use "proxy rule".

**Comment by MagicalWong** [comment]
@HMBSbige It works now, thanks a lot!
