### ISSUE TITLE
[BUG]Win 10后台出现多个“HTTP Auto Proxy..."进程

### ISSUE THREAD

**Issue by martin0607** [HMBSbige/ShadowsocksR-Windows#123]
**描述 bug**

Win 10后台出现多个“HTTP Auto Proxy..."进程

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 可能是推出程序再打开

**截图**

![批注 2019-10-26 232039](https://user-images.githubusercontent.com/32560181/67621941-45449600-f847-11e9-8bfc-7a6099406aa0.jpg)

**环境**

 - 系统：Windows 10 1809
 - 程序版本：5.1.5.0 net48 x64

**Comment by HMBSbige** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows/issues/8#issuecomment-489397756
