### ISSUE TITLE
[BUG]选项-开机自动启动打勾后自动取消

### ISSUE THREAD

**Issue by SakigamiYang** [HMBSbige/ShadowsocksR-Windows#126]
**描述 bug**

在选项中给开机自动启动打钩以后点击“应用”，打勾自动取消。如果点“确定”，在打开设置窗口可以发现配置没有生效。

**环境**

 - 系统：Windows 10 1809
 - 程序版本：V5.1.5

**Comment by SakigamiYang** [comment]
你这玩意儿还有日志呐！我又不懂的编程我哪知道有日志，你看其它几个issue有几个提供日志的。不面向普通用户吗？

**Comment by HMBSbige** [comment]
这里是 GitHub

**Comment by HMBSbige** [comment]
![image](https://user-images.githubusercontent.com/19153265/67919803-d071b300-fbdc-11e9-9750-365027443e1d.png)

**Comment by HMBSbige** [comment]
http://sakigami-yang.me/2019/09/10/5-steps-for-asking-good-questions/
