### ISSUE TITLE
[BUG]pac文件更新为绕过大陆域名和IP后访问特定网站不生效，必须先切到全局再切回PAC

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#127]
原本PAC是GFWLIST，无法访问此站：https://www.rakuten.co.jp/
将pac切换为绕过大陆域名和IP后，还是不能访问，但是切换成全局模式后，可以访问了，此时再从全局模式再切换回 PAC模式，正常访问。

**Comment by HMBSbige** [comment]
无法复现，需要提供日志

**Comment by anticpc** [comment]
> 原本PAC是GFWLIST，无法访问此站：https://www.rakuten.co.jp/
> 将pac切换为绕过大陆域名和IP后，还是不能访问，但是切换成全局模式后，可以访问了，此时再从全局模式再切换回 PAC模式，正常访问。

我从谷歌进，显示 Reference #18.aceb4668.1572485154.330c3a12，不论全局还是pac
![image](https://user-images.githubusercontent.com/32192140/67911416-7283a200-fbc1-11e9-91ec-ea2161f79646.png)
![image](https://user-images.githubusercontent.com/32192140/67911513-c7bfb380-fbc1-11e9-9ecf-4ac301589650.png)

**Comment by anticpc** [comment]
可能是网站的问题
