### ISSUE TITLE
小白，问一下开发者更新是怎么样的

### ISSUE THREAD

**Issue by ymg0827965** [HMBSbige/ShadowsocksR-Windows#130]
是将旧文件用新文件替换还是怎么样，还是能将客户端版本进行直接更新，希望能告知一下，谢谢了

**Comment by HMBSbige** [comment]
@ymg0827965 每次更新前仔细阅读上面的更新说明，一般情况是可以直接覆盖替换

**Comment by ymg0827965** [comment]
关键新版本下载下来就可以直接使用，覆盖更新是不是除了保留部分数据就没其他作用了

Bruce Wayne <notifications@github.com> 于 2019年10月31日周四 16:46写道：

**Comment by HMBSbige** [comment]
@ymg0827965 不覆盖的话，每次更新都重新配置不累吗？

**Comment by ymg0827965** [comment]
我的意思是说您提供了4个包，是用体积小的替换还是都要用大体积的覆盖

Bruce Wayne <notifications@github.com> 于 2019年10月31日周四 16:57写道：

**Comment by HMBSbige** [comment]
@ymg0827965 所以说要熟读上面的更新说明啊，上面不是写了不同版本的区别了吗

**Comment by ymg0827965** [comment]
没注意，现在看到了，麻烦了

Bruce Wayne <notifications@github.com> 于 2019年10月31日周四 17:08写道：
