### ISSUE TITLE
是否有合并ss/ssr的可能性?

### ISSUE THREAD

**Issue by anticpc** [HMBSbige/ShadowsocksR-Windows#132]
**描述您想要的解决方案**

因节点开启隧道加密传输，目前仅支持ss和v2ray (据说后续支持ssr也会有难度)，遂有此想法 ···

**Comment by anticpc** [comment]
还有个小问题，5.1.5版本无法检测到5.1.6的更新

**Comment by HMBSbige** [comment]
> **描述您想要的解决方案**
> 
> 因节点开启隧道加密传输，目前仅支持ss和v2ray (据说后续支持ssr也会有难度)，遂有此想法 ···

等完成 AEAD 和 SIP003，其实也相当于合并了吧，虽然进度咕咕咕



> 还有个小问题，5.1.5版本无法检测到5.1.6的更新

那是你没选上测试版更新
