### ISSUE TITLE
[BUG]报错（貌似和steam冲突）

### ISSUE THREAD

**Issue by kasusa** [HMBSbige/ShadowsocksR-Windows#133]
**描述 bug**

小飞机就报错停止运行

**如何复现**

只要同时打开两个软件就会出现这个问题。
steam并不会收到影响

**截图**

![image](https://user-images.githubusercontent.com/49443405/68079465-fab5b180-fe24-11e9-8398-260652983ba6.png)

**环境**

 - 系统：[如 Windows 10 1903]
 - 程序版本：[如 5.1.5 .Net Core SelfContained x64]

**Comment by HMBSbige** [comment]
@kasusa 这是运行库被清了，换net48或netcore的版本。跟steam没有任何关系
