### ISSUE TITLE
大量HTTP Auto Proxy Detection Worker Process进程堆积

### ISSUE THREAD

**Issue by bingotl** [HMBSbige/ShadowsocksR-Windows#134]
简单来说，1809版的Windows 10上，每次开启pac，都会出现一个HTTP Auto Proxy Detection Worker Process进程，会一直堆积，结束不掉要重启。

相关资料：
https://github.com/shadowsocks/shadowsocks-windows/issues/1979
解决方法：
https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/
https://github.com/shadowsocks/shadowsocks-windows/pull/2208

**Comment by bingotl** [comment]
http://127.0.0.1:1080/pac?t=201911060031576835
由于t参数每次都不一样，系统监控到有新的代理链接，就会启动一个HTTP Auto Proxy Detection Worker Process进程，所以会造成堆叠。这个是1809版win的bug，其他版本貌似已经不会出现。

**Comment by HMBSbige** [comment]
Duplicate of #8

**Comment by bingotl** [comment]
如果我自己改代码，把t参数固定http://127.0.0.1:1080/pac?t=2019，就不会出现这个bug，这样会不会影响代理使用

**Comment by HMBSbige** [comment]
@bingotl timestamp一定要加的，许多基于系统代理的应用只会监听pac地址的变化。

这种系统的锅，建议升级系统
