### ISSUE TITLE
[BUG]在windows10下使用PAC模式，进程不断增加

### ISSUE THREAD

**Issue by hsj1992** [HMBSbige/ShadowsocksR-Windows#135]
**描述 bug**

 Windows 10 下使用软件并启用PAC模式，打开任务管理器，会发现有大量“HTTP Auto Proxy Detection Worker Process”进程。

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. windows10下使用。
2. 启用PAC模式。

**预期行为**

HTTP Auto Proxy Detection Worker Process 进程即pacjsworker.exe，随着使用不断增加数量。

**截图**

![image](https://user-images.githubusercontent.com/4816005/68259521-fda6e100-0074-11ea-9716-b2a9fb1131ac.png)

**环境**

 - 系统：Windows 10 1903

 - 程序版本：ShadowsocksR-net48-5.1.6.2
 
**其它内容**

相关内容：
[关于 Windows 10 SS 客户端出现大量进程的解决办法](https://blog.dun.im/anonymous/%E5%85%B3%E4%BA%8E-windows-10-ss-%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%87%BA%E7%8E%B0%E5%A4%A7%E9%87%8F%E8%BF%9B%E7%A8%8B%E7%9A%84%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95.html)

**Comment by HMBSbige** [comment]
Duplicate of #8
