### ISSUE TITLE
能否在服务器列表页直接选择节点

### ISSUE THREAD

**Issue by ssyangchn** [HMBSbige/ShadowsocksR-Windows#136]
每次切换服务器都要右键->服务器->分组，实在是繁琐，能否在服务器列表->服务器编辑页增加个【选择】按钮直接切换呢？

**Comment by HMBSbige** [comment]
@ssyangchn 在 服务器记录 窗口切换，单击服务器那列就行了

**Comment by ssyangchn** [comment]
> @ssyangchn 在 服务器记录 窗口切换，单击服务器那列就行了

用了2年小飞机竟然不知道这个功能👍👍👍
