### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 2han9wen71an** [HMBSbige/ShadowsocksR-Windows#137]
**描述 bug**

在win10 ltsc2019上使用pac模式运行后占用大量cpu，并且任务管理器不能强行停止该进程，只能重启解决，使用全局模式cpu占用正常

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 订阅服务器
2. 更新pac为gfwlist
3. 系统代理改为pac模式

**截图**

![MkEzod.png](https://s2.ax1x.com/2019/11/07/MkEzod.png)

**环境**

 - 系统：[ Windows 10 ltsc2019]
 - 浏览器：[如 Chrome 78.0.3904.87]
 - 程序版本：[ShadowsocksR-netcore-win64-5.1.6.2]

**Comment by HMBSbige** [comment]
Duplicate of #8
