### ISSUE TITLE
[BUG]连接统计界面手动禁用的序号为1 的连接会不定时自己打开

### ISSUE THREAD

**Issue by ouyangxxx** [HMBSbige/ShadowsocksR-Windows#138]
感谢大佬的更新维护.

使用中遇到了一个小bug.版本5.1.6.2
如题描述在连接统计(服务器记录)界面手动把序号为1的连接(第一条连接)最前面点为红色禁用连接,会不定时自己打开. 
其他序号的连接没有这个问题,能正常手动禁用启用

**Comment by HMBSbige** [comment]
@ouyangxxx 一看就知道你机场第一个节点是显示流量信息，每次更新订阅都会更新信息，当然会自己启用咯😂
