### ISSUE TITLE
[BUG]服务器负载均衡有问题

### ISSUE THREAD

**Issue by painter1989** [HMBSbige/ShadowsocksR-Windows#139]
多节点用服务器负载均衡，打开网站连接网络响应慢，时间久才有网络连接打开，偶尔直接没速度，用4.7ssr的版本反而没有出现这个问题。

**Comment by HMBSbige** [comment]
自己节点的问题

![](https://user-images.githubusercontent.com/19153265/68524232-4ffb3280-02ff-11ea-8a3b-6adc1c21140c.png)
