### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by wxlg1117** [HMBSbige/ShadowsocksR-Windows#14]
今儿个测试来测试去的时候发现的:
新版那个SSR链接默认不选中了,导致我的SSR配置复制到新启动的无配置客户端测试使用的时候浏览器报错误...还以为我服务器啊之类的有问题了.

发现控件那默认是选中的,求大神告知代码怎么改动为默认SSR链接选中;

发现 以SS链接 复制过来后 群组名和备注都为空,气泡显示第二栏就显示一个冒号,大神看看能实现 群组名和备注 都为空则不显示第二栏;

![Snipaste_2019-05-10_16-34-45](https://user-images.githubusercontent.com/9752596/57513748-92888600-7341-11e9-8d9b-e3e20b42ae7c.png)

**Comment by HMBSbige** [comment]
bug  好多啊555

**Comment by HMBSbige** [comment]
把旧配置复制到新的无配置客户端会有问题？不知道你第一个问题是什么意思

你先试试 [nightly build](https://ci.appveyor.com/project/HMBSbige/shadowsocksr-windows/build/artifacts) 行不行
