### ISSUE TITLE
PublishReadyToRun？

### ISSUE THREAD

**Issue by imba-tjd** [HMBSbige/ShadowsocksR-Windows#141]
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-6/#user-content-optimize-your-net-core-apps-with-readytorun-images

有性能提升，然而必须要加RID。

**Comment by HMBSbige** [comment]
这就是 self contained 版本吧，还是说有什么区别？

**Comment by imba-tjd** [comment]
我不知道深入的区别……

> Note: ReadyToRun is currently only supported for self-contained apps. It will be enabled for framework-dependent apps in a later preview.

根据这句话，应该和self-contained不是一个意思

**Comment by HMBSbige** [comment]
从编译参数来看是 self-contained 的一个参数

+减少程序启动时间和内存使用
-增加程序大小
