### ISSUE TITLE
github网站用户头像无法显示

### ISSUE THREAD

**Issue by tianjg** [HMBSbige/ShadowsocksR-Windows#144]
github网站中用户头像无法显示。4.7版无这种问题。
BUG如下图：

![image](https://user-images.githubusercontent.com/29768449/68726646-15dea900-05fd-11ea-8db9-407bb377dbd6.png)

**Comment by ShangyinGao** [comment]
if you are using a proxy, try to add 'githubusercontent.com' to the PAC file
