### ISSUE TITLE
[BUG]四个版本中，net48在5.0.0.1之后版本检测更新会失败

### ISSUE THREAD

**Issue by yuningning520** [HMBSbige/ShadowsocksR-Windows#146]
以前检测更新还是正常的，不知道哪个系统更新后就不行了
我重新下载5.1.7的四个版本用相同节点试检测更新，除去net48会直接失败，其他三个延迟高点也完成
测试截图 https://imgur.com/a/hC51MFj
然后我向下都试了试，net48的到5.0.0.1才检测成功，下边是用的节点
`ssr://dXMyLnNzcnN1Yi54eXo6OTk5OTpvcmlnaW46cmM0LW1kNTpwbGFpbjpkQzV0WlM5VFUxSlRWVUkvP29iZnNwYXJhbT0mcmVtYXJrcz01Ny03NWFLWjVZV2FNelkyTGpnMzU3Nk81WnU5Jmdyb3VwPTU3Nk81WnU5`
顺手搜了一下 **请求被中止: 未能创建 SSL/TLS 安全通道**，是个.net4里常见的问题
这是随便找的解决方法，不会编程不知道有没有用
https://www.itsvse.com/thread-7612-1-1.html

其他信息
net版本 v4.8.03752 （528040）
系统版本 w10 1909 （18363.476）

Microsoft .NET Framework 4 Client Profile
KB2468871
KB2468871v2
KB2478063
KB2533523
KB2544514
KB2600211
KB2600217
Microsoft .NET Framework 4 Extended
KB2468871
KB2468871v2
KB2478063
KB2533523
KB2544514
KB2600211
KB2600217

**Comment by HMBSbige** [comment]
调试了一下，这是微软的[锅](https://support.microsoft.com/zh-cn/help/4528489/transport-layer-security-tls-connections-might-fail-or-timeout-when-co)

**Comment by yuningning520** [comment]
用抓包工具时，安装抓包工具的https解密信任证书后就正常了，退出抓包工具后还是失败
