### ISSUE TITLE
[BUG] SSR Windows 是否至今仍不支持 UDP Relay？（监听端口列表里无相应UDP端口）

### ISSUE THREAD

**Issue by poly-1** [HMBSbige/ShadowsocksR-Windows#149]
## 环境
程序版本：ShadowsocksR-net48-5.1.6.2.zip

## 问题描述

按理说SSR本质是一个Socks5代理，应该是支持UDP转发的。但是使用Windows的`netstat -an`命令，发现只有相应的TCP端口在监听，未在列表里找到相应的UDP端口。这样软件显然无法实现UDP转发的功能，实际测试亦如此。

作为对比，如果使用 shadowsocks windows，则可以同时在列表里观察到TCP和UDP端口。

此外，编辑服务器设置里面的Adv. Settings（高级选项）是否应废弃？因为
- 本地UDP端口如果都没有监听，则编辑服务器里面的UDP端口（这个应该是设置的远程的？）选项则没有意义；
- 另一个选项，UDP over TCP应该也需要SSR服务端支持，但目前似乎没有SSR服务端支持UDP over TCP这个特性。

**Comment by HMBSbige** [comment]
Socks5 并不是直接监听 UDP 的，需要通过 TCP 连过去，然后申请 UDP 通讯端口

高级选项里等重做的时候应该就移除了

**Comment by ConnectionRefused** [comment]
[RFC1928](https://tools.ietf.org/html/rfc1928)

**Comment by ConnectionRefused** [comment]
```
UDP ASSOCIATE

   The UDP ASSOCIATE request is used to establish an association within
   the UDP relay process to handle UDP datagrams.  The DST.ADDR and
   DST.PORT fields contain the address and port that the client expects
   to use to send UDP datagrams on for the association.  The server MAY
   use this information to limit access to the association.  If the
   client is not in possesion of the information at the time of the UDP
   ASSOCIATE, the client MUST use a port number and address of all
   zeros.

   A UDP association terminates when the TCP connection that the UDP
   ASSOCIATE request arrived on terminates.

   In the reply to a UDP ASSOCIATE request, the BND.PORT and BND.ADDR
   fields indicate the port number/address where the client MUST send
   UDP request messages to be relayed.
```

**Comment by poly-1** [comment]
@ConnectionRefused 谢谢提供的RFC1928文档。文档的Section 7里面说了UDP 包的格式，文档也说了UDP代理的流程：
- 通过TCP端口向socks5服务器申请UDP代理
- socks5服务器返回**允许的UDP代理地址与UDP端口**
- 客户端向**服务器返回的UDP端口**发送UDP包实现UDP relay

所以，确实需要往服务器的UDP端口发送数据。按照shadowsocks的设计原则，把Socks5代理的其中一半放到本地，那么本地确实应该监听UDP端口，如果不监听，则不然无法代理UDP datagrams。 @HMBSbige

**Comment by HMBSbige** [comment]
@poly-1 确实个鬼哦，自己认真研究一下吧

**Comment by poly-1** [comment]
我在找一张流程图吧。要实现UDP Relay，首先是通过TCP连接进行UDP Relay申请，然后TCP连接作为控制通道控制申请到的这条UDP通道的通断。最终的数据全部通过UDP协议发送，如果你还是认为不用监听UDP，我也无语了。 @HMBSbige @ConnectionRefused 
![Socks5 Model](https://user-images.githubusercontent.com/57432575/69349032-19011700-0c45-11ea-8452-138c6dde1867.png)

具体来说，shadowsocks包括sslocal和ssserver，我们首先需要跟sslocal通信（即上图的下半部分），所以必须sslocal需要开放一个UDP端口。

至于sslocal与ssserver之间UDP包如何通信，就看shadowsocks协议里面怎么定义得了，可以只用TCP也可以TCP/UDP都用。如果只用TCP的话，那么编辑服务器设置里面的Adv. Settings（高级选项）应该就是为这个服务的，应该勾上UDP over TCP（但目前似乎没有SSR服务端支持这个特性）。

**Comment by poly-1** [comment]
花了半天总算研究明白了，*没有Bug*，这是Shadowsocks windows和ShadowsocksR windows在实现本地Socks5代理上的不同引起了我的误解。

ShadowsocksR windows实现代理UDP的方式如下：
- 通过预先指定的TCP端口向本地socks5服务器申请代理UDP；
- socks5服务器给客户端返回另一个**高位UDP端口**作为UDP转发端口；
- 客户端可以向这个UDP端口发送UDP包来实现UDP relay；
- 一旦转发结束，该新分配UDP端口马上关闭（所以通过`netstat`看不到了）。

Shadowsocks windows实现代理UDP的方式如下：
- 通过预先指定的TCP端口向本地socks5服务器申请代理UDP；
- socks5服务器给客户端返回一个与指定的TCP端口相同的UDP端口作为UDP转发端口；
- 客户端可以向这个UDP端口发送UDP包来实现UDP relay
- 该**固定的UDP端口**将一直处于监听状态（不关闭，所以通过`netstat`可以看到）。

我之前下意识的认为他们这个功能的实现是一样的。

我不是不愿意去学习研究，希望两位大佬 @HMBSbige @ConnectionRefused  以后回答小白的时候至少多给点提示，比如可以提示一下在ShadowsocksR上大概是怎么实现的，代码在哪个文件之类的，而不是有点爱理不理的态度，这样会让人比较寒心。
