### ISSUE TITLE
能不能把user.rule和chn_ip.txt内置进去(pac下的代理)

### ISSUE THREAD

**Issue by lan542662** [HMBSbige/ShadowsocksR-Windows#15]
现在pac用的白名单模式，加上局域网ip段，配合user.rule使用，这样效率最高，但是可能我配置原因，有时候网站第一次打不开，第二次才打得开，我是按照以前的pac 绕过china模式，直接修改的，可能改乱了。
另外linux下目前只有pac模式...electron-ssr作者无能为力，您能在那弄个ip分流功能吗

**Comment by HMBSbige** [comment]
不是很懂，`user.rule` 本来就是用来自定义的，`chn_ip.txt`可以自己下或者自定义，为什么要内置

你 PAC 更新成 `绕过大陆域名和IP` 是有问题还是什么？

**Comment by lan542662** [comment]
> 不是很懂，`user.rule` 本来就是用来自定义的，`chn_ip.txt`可以自己下或者自定义，为什么要内置
> 
> 你 PAC 更新成 `绕过大陆域名和IP` 是有问题还是什么？

如果设置成gfw模式，那么user.rule就失效了。他只按黑名单。其余直连，user.rule不走了。
如果是绕过模式，就是，除了pac中地址(china域名)，其余默认代理，这样uer.rule就起作用了。然后继续用china ip段覆盖全局。

我想说的，pac中设置成里面的可以有域名黑名单和白名单，然后他还走user.rule.

**Comment by HMBSbige** [comment]
那么你自己自定义呗

**Comment by lan542662** [comment]
> 那么你自己自定义呗

一年前就关注你的一些规则了，很不错。不瞒你说，我现在是在绕过中国域名的基础上，把域名全换成黑名单了。胡乱改了。把direct改成wall_proxy()不知道有没有造成混乱，不过目前可以达到效果。另外linux下你能帮忙最好拉，哈哈哈。

**Comment by HMBSbige** [comment]
不存在的1551
