### ISSUE TITLE
[功能请求] 希望可以增加节点批量测速功能。希望不要被拉到憨憨里。

### ISSUE THREAD

**Issue by yoyoyosoro** [HMBSbige/ShadowsocksR-Windows#150]
希望可以增加一个一键批量测速功能，同https://github.com/mobier/shadowsocksr-speed/issues

随着封锁变严格、机场节点数量多变化快...通过批量测速而不是ping挑一个真正适合自己环境的节点应该是很多用户迫切需要的功能。

可惜隔壁的这个ssr-speed需要单独下载软件、安装python、还要打命令，对普通用户来说太噩梦了，对着教程都操作不上都算正常。如果可以集成到ssr客户端里，可以极大地方便用户。

**Comment by HMBSbige** [comment]
你既然看了之前的issue就应该知道是不可能做测速的
