### ISSUE TITLE
[BUG] 无法正常访问外网

### ISSUE THREAD

**Issue by lincuncuncaogoudan** [HMBSbige/ShadowsocksR-Windows#151]
**描述 bug**

按照教程操作后无法未完成翻墙，无论是谷歌学术还是Youtube

**截图**

![image](https://user-images.githubusercontent.com/29887717/69642385-a22ca980-109c-11ea-8293-cd03f5cc4d1f.png)

**环境**

 - 系统：[如 Windows 10 ]
 - 浏览器：[如 Chrome ]
 - 程序版本：[ShadowsocksR-Portable-Win64-5.1.7.1]

**Comment by HMBSbige** [comment]
我觉得是你没正确选择系统代理，这种问题还是问你的机场主
