### ISSUE TITLE
[BUG]开启软件出现大量HTTP Auto Proxy Detection Worker Process进程

### ISSUE THREAD

**Issue by Lovezhang23** [HMBSbige/ShadowsocksR-Windows#153]
**描述 bug**

开启软件出现大量HTTP Auto Proxy Detection Worker Process进程，PAC模式，代理规则：绕过局域网和大陆。网络上有人有4.9.2的解决方案，供作者参考。https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/（系统出现大量HTTP Auto Proxy Detection Worker Process）
**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 
2. 
3. 

**预期行为**

简要描述进行以上操作后预期的脚本行为

**截图**
![image](https://user-images.githubusercontent.com/57610706/69721769-884c9e80-1150-11ea-9acc-0b732d9ddcc6.png)

如果可以，请添加屏幕截图以帮助解释您的问题

**环境**

 - 系统：[如 Windows 10 1909]
 - 浏览器：[如 (Chromium 74.0.3729.169)]
 - 程序版本：[如 5.0.0.0 .Net Core SelfContained x64]
 
**其它内容**

在此添加有关此问题的任何其它内容。
最好能贴上相关的日志

**Comment by HMBSbige** [comment]
Duplicate of #8
