### ISSUE TITLE
[功能建议]Gfwlist用户规则打开略繁琐

### ISSUE THREAD

**Issue by ThinkNaive** [HMBSbige/ShadowsocksR-Windows#16]
使用PAC模式GFWList时，不少网站需要手动添加到代理列表。
希望点击“编辑GFWList的用户规则”时直接打开对应的规则文件，而不是定位到文件夹。
如果再关闭规则文件时能自动更新PAC就再好不过了。

**Comment by HMBSbige** [comment]
试试[这个](https://ci.appveyor.com/project/HMBSbige/shadowsocksr-windows/builds/24621313/artifacts)

**Comment by ThinkNaive** [comment]
很好用，多谢大神！
