### ISSUE TITLE
绕过局域网和大陆和绕过局域网和非大陆无效[BUG]

### ISSUE THREAD

**Issue by VeTsgG** [HMBSbige/ShadowsocksR-Windows#161]
**描述 bug**

简要描述所遇到的bug

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 系统代理选全局
2. 规则设置-代理规则选择绕过局域网和大陆

绕过局域网是有效的 选择其他2项时都没用 不能做到正确的分配

**Comment by HMBSbige** [comment]
@VeTsgG 请按照模版提供系统参数

**Comment by VeTsgG** [comment]
- 系统：Windows10 1909 build 18362.19h1
 - 浏览器：chrome  78.0.3904.108
 - 程序版本：net48-5.1.8
@HMBSbige

**Comment by VeTsgG** [comment]
![屏幕截图(3)](https://user-images.githubusercontent.com/12571320/69930053-65c5d700-14fc-11ea-91dc-be635ecf0d11.png)

**Comment by HMBSbige** [comment]
@VeTsgG 需要提供连接时的日志

**Comment by VeTsgG** [comment]
@HMBSbige 这一段？
[Error] System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 221.180.xxx.xxx:443
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Service.Socks5Forwarder.Handler.ConnectCallback(IAsyncResult ar)

**Comment by HMBSbige** [comment]
@VeTsgG 需要提供更多日志...

我建议你还是进tg群问吧

**Comment by HMBSbige** [comment]
使用代理规则时请确保使用的是无污染的 DNS
