### ISSUE TITLE
[BUG] 无法启动: 0xc000007b

### ISSUE THREAD

**Issue by dingwen07** [HMBSbige/ShadowsocksR-Windows#163]
![截图](https://user-images.githubusercontent.com/29778171/70013498-d0d1e500-15b2-11ea-811e-3a03c3f5b2c0.PNG)

**环境**

 - 系统：Windows 7 SP1
 - 程序版本：ShadowsocksR-Portable-Win64-5.1.8

**Comment by dingwen07** [comment]
自从5.1.7.2开始出现这个错误
所有32位版本均能正常运行
操作系统是64位的

**Comment by HMBSbige** [comment]
Win7 无法复现

**Comment by HMBSbige** [comment]
使用带运行库版本
