### ISSUE TITLE
[BUG] 无法运行: 停止工作

### ISSUE THREAD

**Issue by dingwen07** [HMBSbige/ShadowsocksR-Windows#164]
[2019-12-03 10:04:24] [Error] System.IO.FileLoadException: Could not load file or assembly 'Syncfusion.Licensing, Version=17.3.0.29, Culture=neutral, PublicKeyToken=632609b4d040f6b4'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Syncfusion.Licensing, Version=17.3.0.29, Culture=neutral, PublicKeyToken=632609b4d040f6b4'
   at Shadowsocks.Program.Main(String[] args) in D:\Cloud\Git\ShadowsocksR-Windows\shadowsocks-csharp\Program.cs:line 55

注: 与#163不同

**Comment by HMBSbige** [comment]
重新下载

**Comment by dingwen07** [comment]
已经重新下载
5.1.8出错
前一版本无问题

**Comment by HMBSbige** [comment]
> 已经重新下载
> 5.1.8出错
> 前一版本无问题

系统环境呢？

**Comment by dingwen07** [comment]
> > 已经重新下载
> > 5.1.8出错
> > 前一版本无问题
> 
> 系统环境呢？

Microsoft Windows 7 Ultimate 
6.1.7601 Service Pack 1 Build 7601
[systeminfo.txt](https://github.com/HMBSbige/ShadowsocksR-Windows/files/3914233/systeminfo.txt)

**Comment by HMBSbige** [comment]
确定一下ShA-256 `ShadowsocksR-Portable-Win64-5.1.8.7z`

`561DA28250E2F61FCFF6E34431580C2ED14CD4D072E8DC020E150ED0D974189E`

如果一样的，建议安装运行库，使用不带运行库的版本

**Comment by dingwen07** [comment]
已确认旧版本启动后日志也会出现那样的错误

**Comment by dingwen07** [comment]
导致崩溃的错误日志
日志名称:          Application
来源:            Application Error
日期:            2019/12/3 星期二 10:43:54
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           F3
描述:
错误应用程序名称: ShadowsocksR.exe，版本: 5.1.8.0，时间戳: 0x5d7bb0cb
错误模块名称: KERNELBASE.dll，版本: 6.1.7601.24441，时间戳: 0x5cb93873
异常代码: 0xe0434352
错误偏移量: 0x0000c5af
错误进程 ID: 0x15c0
错误应用程序启动时间: 0x01d5a983808328fc
错误应用程序路径: C:\Users\Administrator\Downloads\ShadowsocksR-Portable-Win32-5.1.8\ShadowsocksR\ShadowsocksR.exe
错误模块路径: C:\Windows\syswow64\KERNELBASE.dll
报告 ID: be4b3b2c-1576-11ea-9844-5800e3b2c904
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-12-03T02:43:54.000000000Z" />
    <EventRecordID>2165</EventRecordID>
    <Channel>Application</Channel>
    <Computer>F3</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ShadowsocksR.exe</Data>
    <Data>5.1.8.0</Data>
    <Data>5d7bb0cb</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.24441</Data>
    <Data>5cb93873</Data>
    <Data>e0434352</Data>
    <Data>0000c5af</Data>
    <Data>15c0</Data>
    <Data>01d5a983808328fc</Data>
    <Data>C:\Users\Administrator\Downloads\ShadowsocksR-Portable-Win32-5.1.8\ShadowsocksR\ShadowsocksR.exe</Data>
    <Data>C:\Windows\syswow64\KERNELBASE.dll</Data>
    <Data>be4b3b2c-1576-11ea-9844-5800e3b2c904</Data>
  </EventData>
</Event>

**Comment by HMBSbige** [comment]
应该是系统问题

我全新安装的 Win7 没什么问题

建议安装自行运行库后试试那两个小的版本

#163 同理
