### ISSUE TITLE
[BUG]net48 5.1.8，点击连接统计中的清空会未响应

### ISSUE THREAD

**Issue by yuningning520** [HMBSbige/ShadowsocksR-Windows#166]
试了试别的版本，感觉是net48因为微软的锅或者系统问题什么的
总之我换netcore了，大概不会来打扰了x

**Comment by HMBSbige** [comment]
net48版本 `ConcurrentQueue` 没有 `Clear()` 

自实现的 `Clear()` 引起的死锁
