### ISSUE TITLE
[BUG] 5.1.8.1 版本更新订阅无法更新，一直失败，5.1.8 版本更新正常

### ISSUE THREAD

**Issue by yudar1024** [HMBSbige/ShadowsocksR-Windows#167]
**描述 bug**

简要描述所遇到的bug

**如何复现**

说明您在进行了怎样的操作后出现了bug：

在5.1.8.1版本中更新订阅，显示更新失败，使用5.1.8版本更新订阅，更新正常。

**预期行为**

简要描述进行以上操作后预期的脚本行为

**截图**

如果可以，请添加屏幕截图以帮助解释您的问题

**环境**

 - 系统：[如 Windows 10 1809]
windows10 1909
 - 浏览器：[如 Chrome 74.0.3729.157，无关则删除]
 - 程序版本：[如 5.0.0.0 .Net Core SelfContained x64]
 
**其它内容**

在此添加有关此问题的任何其它内容。
最好能贴上相关的日志

**Comment by HMBSbige** [comment]
@yudar1024 所有连接问题都要提供日志

**Comment by yudar1024** [comment]
[2019-12-04 09:18:58] [Error] System.ArgumentException: 当前仅支持 HTTP/1.0 和 HTTP/1.1 版本的请求。
参数名: value
   在 System.Net.HttpWebRequest.set_ProtocolVersion(Version value)
   在 System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   在 System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Shadowsocks.Controller.HttpRequest.HttpRequest.<GetAsync>d__3.MoveNext() 位置 D:\a\ShadowsocksR-Windows\ShadowsocksR-Windows\shadowsocks-csharp\Controller\HttpRequest\HttpRequest.cs:行号 30
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Shadowsocks.Controller.HttpRequest.HttpRequest.<DirectGetAsync>d__6.MoveNext() 位置 D:\a\ShadowsocksR-Windows\ShadowsocksR-Windows\shadowsocks-csharp\Controller\HttpRequest\HttpRequest.cs:行号 87
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Shadowsocks.Controller.HttpRequest.HttpRequest.<AutoGetAsync>d__5.MoveNext() 位置 D:\a\ShadowsocksR-Windows\ShadowsocksR-Windows\shadowsocks-csharp\Controller\HttpRequest\HttpRequest.cs:行号 80
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Shadowsocks.Controller.HttpRequest.UpdateChecker.<Check>d__18.MoveNext() 位置 D:\a\ShadowsocksR-Windows\ShadowsocksR-Windows\shadowsocks-csharp\Controller\HttpRequest\UpdateChecker.cs:行号 55

**Comment by HMBSbige** [comment]
@yudar1024 按照模版填写系统环境...

**Comment by yudar1024** [comment]
描述 bug

无法更新订阅

如何复现

在5.1.8.1版本中选择 更新订阅，显示更新失败，使用5.1.8版本更新订阅，更新正常。

预期行为

更新正常。



环境

系统：windows10 1909

程序版本：5.1.8.1
其它内容

日志
[2019-12-04 09:18:58] [Error] System.ArgumentException: 当前仅支持 HTTP/1.0 和 HTTP/1.1 版本的请求。
参数名: value
在 System.Net.HttpWebRequest.set_ProtocolVersion(Version value)
在 System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
在 System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
在 Shadowsocks.Controller.HttpRequest.HttpRequest.d__3.MoveNext() 位置 D:\a\ShadowsocksR-Windows\ShadowsocksR-Windows\shadowsocks-csharp\Controller\HttpRequest\HttpRequest.cs:行号 30
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
在 Shadowsocks.Controller.HttpRequest.HttpRequest.d__6.MoveNext() 位置 D:\a\ShadowsocksR-Windows\ShadowsocksR-Windows\shadowsocks-csharp\Controller\HttpRequest\HttpRequest.cs:行号 87
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
在 Shadowsocks.Controller.HttpRequest.HttpRequest.d__5.MoveNext() 位置 D:\a\ShadowsocksR-Windows\ShadowsocksR-Windows\shadowsocks-csharp\Controller\HttpRequest\HttpRequest.cs:行号 80
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
在 Shadowsocks.Controller.HttpRequest.UpdateChecker.d__18.MoveNext() 位置 D:\a\ShadowsocksR-Windows\ShadowsocksR-Windows\shadowsocks-csharp\Controller\HttpRequest\UpdateChecker.cs:行号 55

**Comment by HMBSbige** [comment]
@yudar1024 然后你还没说用的是5.1.8.1的哪个release😂

**Comment by yudar1024** [comment]
ShadowsocksR-net48-5.1.8.1.zip ，
> @yudar1024 然后你还没说用的是5.1.8.1的哪个release😂

我也算是良心用户了。哈哈哈
