### ISSUE TITLE
无法记录日志/ No logs  版本 4.9.5.1

### ISSUE THREAD

**Issue by Utopio-sphere** [HMBSbige/ShadowsocksR-Windows#17]
#### 新版本更新后，图标栏右键“查看日志”界面不显示日志
查看了目录下的日志，日志的记录到更新前的5月8日为止，此前的所有连接均有记录，但是更新以后shadowsocks似乎没有再记录日志，同样也找不到新的日志，可能是日志写入的时候路径编码出了异常，导致程序里程序外不仅无法写入日志，也无法读取曾经的日志

最后一条日志：
文件路径：
C:\Software\ShadowsocksR\temp\shadowsocks_2019-05.log

[2019-05-08 14:51:43] [Info] Disconnect 104.31.76.117:443

在此之后我应该是进行了更新，更新后再无日志

**Comment by HMBSbige** [comment]
选项设置里是否开启日志

**Comment by wxlg1117** [comment]
选项设置里开启日志后还得重启客户端...不然还是没有
