### ISSUE TITLE
 不清楚订阅机制是什么，但是存在订阅地址无法解析时，节点无法连接的情况

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#170]
不知道算不算是BUG，所以提到other issue里。
因为出现的不频繁。改完用户的DNS就OK了。也不知道什么机制触发的这个问题。

场景如下：
1.用户添加了订阅，更新成功，节点列表有节点，可以正常连接。
2.用户关机重启系统后，客户端订阅日志里提示订阅地址 connect fail，反复reconnect，然后我远程后发现是因为用户本地无法解析出 订阅地址，节点也无法连接，更换 223.5.5.5 后解析正常、订阅正常，但是节点还是无法连接，排查过VNET后端，发现节点上的用户是存在的。还有，如果不强制退出客户端重开，则订阅会一直失败。（这不知道算不算bug，哈哈）
3.让用户换一个节点（域名不同），连接成功。

猜测：因为c#我是弱鸡，所以不清楚到底是不是win客户端缓存或者dns解析机制引起的bug。也可能是我面板没有正确推送用户到节点（这个狗日的CURL，等我改掉它...）。也有可能是VNET有用户但是无法连的BUG

用户系统：WIN10
用户宽带：北京电信
日志：无，都是一些reconnect 的日志
我：一脸懵逼，已经请求徐sir把VNET加一个 查询 用户 是否已存在的api了。。。日了汪汪队

**Comment by ssrpanel** [comment]
客户端版本：5.1.7.2

**Comment by zfscgy** [comment]
你试试看是不是你的节点没有enable
