### ISSUE TITLE
关于自己定义user-rule.txt不生效的问题

### ISSUE THREAD

**Issue by catterdx** [HMBSbige/ShadowsocksR-Windows#171]
[### 参考你的wiki](https://github.com/HMBSbige/ShadowsocksR-Windows/wiki/Proxy-Rule)
**不清楚是编写失误还是设置失误,并不能生效!另外版本是5.1.8.2.PAC是绕过大陆域名和IP**

![Lily_Screenshot_1575826607](https://user-images.githubusercontent.com/58603950/70393415-6098e880-1a24-11ea-9402-7aaa1da34062.png)
![Lily_Screenshot_1575826258](https://user-images.githubusercontent.com/58603950/70393324-a30df580-1a23-11ea-9f65-cb24ba688463.png)
![Lily_Screenshot_1575826347](https://user-images.githubusercontent.com/58603950/70393339-c769d200-1a23-11ea-959a-68ba968b78a0.png)

**Comment by catterdx** [comment]
因为是小白一个,我又尝试了一下,把PAC更新为GFWLIST时,会自动同步user-rule内容,
![Lily_Screenshot_1575829629](https://user-images.githubusercontent.com/58603950/70394009-7362eb80-1a2b-11ea-91ee-eb7025790a05.png)

**### 但这个格式我依然有些懵**

![Lily_Screenshot_1575829713](https://user-images.githubusercontent.com/58603950/70394024-a311f380-1a2b-11ea-8986-62275276cee0.png)
还有这个注释符号到底是"!"还是"#",我要裂开了.

**Comment by zyOverture** [comment]
user-rule.txt是pac的自定义文件
user.rule是代理规则的自定义文件
你这是在用user.rule的语法写user-rule.txt

**Comment by catterdx** [comment]
> user-rule.txt是pac的自定义文件
> user.rule是代理规则的自定义文件
> 你这是在用user.rule的语法写user-rule.txt
不好意思，你说的我半懂不懂，是不是我的图片没发清楚，我又改了一下，你如果能给我个实例最好。

**Comment by HMBSbige** [comment]
@catterdx 
`user-rule.txt` 是用于 GFWList 的自定义规则，[参考](https://adblockplus.org/en/filter-cheatsheet)
`user.rule` 是用于代理规则的，[Wiki](https://github.com/HMBSbige/ShadowsocksR-Windows/wiki/Proxy-Rule)

**Comment by catterdx** [comment]
我又进行了一些无脑的尝试
系统代理-PAC
pac-gfw
代理规则-全局
修改user.rule.txt会自动同步到pac.txt
规则写
"||ip138.com   
表示设置为被墙,走代理
@@||ip138.com
设置为例外,走直连
按这样好像已经可以达到我想要的效果,纯属愚蠢尝试出来的结果,也许也些地方还是不对.
