### ISSUE TITLE
[BUG]PAC未GFWLIST模式下，打开此网站会报500错误

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#172]
**描述 bug**
打开此网站，报500错误：`http://spring4u.info/index.php`

```
500 Internal Privoxy Error
```

**如何复现**

PAC 更新为最新的GFWLIST，使用全局模式也是一样报这个错误，我记得如果网址不在PAC列表里的话，应该是浏览器无法打开的错误，为啥是500 错误。

**预期行为**
浏览器正常无法访问错误

 - 系统：Windows 10 专业版最新版本号（我也不知道多少）
 - 浏览器：Chrome 78.0.3904.108
 - 程序版本：5.1.8.2 .net Framework 4.8
 
**日志**
[2019-12-13 17:45:39] [Info] Connect spring4u.info:80 via XXXX.COM:8080
[2019-12-13 17:45:39] [Info] Disconnect spring4u.info:80

**Comment by HMBSbige** [comment]
因为是经过代理了，是服务器那边不能访问网站

应该是服务器那边的问题

**Comment by ssrpanel** [comment]
3Q，更换代理服务器的DNS解决
