### ISSUE TITLE
[BUG]订阅更新失败后再成功不会自动更新订阅备注

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#174]
场景：订阅更新失败，默认有一个备注 叫 ：错误
当我再次更新订阅成功后，它的备注没有跟着更新过来

![QQ图片20191216050026.png](https://i.loli.net/2019/12/16/uERI1OrgwoJzVSv.png)

**Comment by ssrpanel** [comment]
在服务器 列表处是对的。但是在订阅设置里是错的

**Comment by ssrpanel** [comment]
今晚通宵。。

**Comment by ssrpanel** [comment]
在编辑服务器列表里的订阅备注也是错的

**Comment by HMBSbige** [comment]
就是这样设计的，允许用户自己改名字，默认使用该订阅第一个分组的备注
