### ISSUE TITLE
[BUG] 开了全局模式以后网易云就连不上网络

### ISSUE THREAD

**Issue by 108678868** [HMBSbige/ShadowsocksR-Windows#178]
描述 bug

开了全局模式以后网易云就连不上网络

环境

    系统：Windows 10 1909
    程序版本：ShadowsocksR-net48-5.1.8.2

**Comment by AmazingDM** [comment]
![image](https://user-images.githubusercontent.com/10679055/71396571-acb77000-2655-11ea-8729-da9933ebbbce.png)
试试

**Comment by AgaigetS** [comment]
那肯定啊，你全局等于在外国访问中国网站，肯定慢了后者直接访问不了。所以你想兼的就用pac。这不是bug。
