### ISSUE TITLE
[BUG]C盘program files及program files(x86)文件夹下无法启动

### ISSUE THREAD

**Issue by k1suke** [HMBSbige/ShadowsocksR-Windows#179]
**描述 bug**

C盘program files及program files(x86)文件夹下无法启动（具体情况为右下角看见图标大约20-30秒后进程消失），右键使用管理员身份可以正常启动，也是此原因开机之后无法自启

**环境**

 - 系统：Windows 10 1909
 - 程序版本：ShadowsocksR-net48-5.1.8.2.zip

其他目录没有问题，有点小强迫症就来反馈下

**Comment by yeiiii** [comment]
我也是这个问题，但之前是没有的，今天晚上重装系统之后就这样了。估计是要少了一些环境导致，但不知道是哪个

**Comment by HMBSbige** [comment]
感觉挺正常的

推荐放在用户目录里
