### ISSUE TITLE
移植到 .NET Core

### ISSUE THREAD

**Issue by HMBSbige** [HMBSbige/ShadowsocksR-Windows#18]
虽然微软没有正式声明，.NET Framework 4.8 很可能是最后的大版本
出处：[音频](https://player.fm/series/the-net-core-podcast/corewf-with-dustin-metzgar)，20:40处

所以我还是想转到 .Net Core 上，.Net Core 3.0 也快 RC 了

.Net Core 版本的好处有很多就不说了，缺点应该就是不再能单文件了，至少现在做不到。目前最少也需要一个`exe`，一个`dll`，一个`json`运行时配置文件。虽然我感觉是无所谓的，反正最后运行时总要释放、调用一堆文件

虽然本项目是我自用的，我还是想听取一些意见或者建议

**本项目中所用到的 .NET Framework API 与 .Net Core 的不同**
- [x] string.GetHashCode();
.Net Core 因为防止哈希洪水攻击等安全原因默认启用随机 Hash 算法。
因本项目某些地方需要保证每次运行时Hash 值一样，所以目前已自实现`string.GetDeterministicHashCode();`
- [x] delegate.BeginInvoke();
.Net Core 编译时不报错，运行时抛出异常（PlatformNotSupported），原因：https://github.com/dotnet/corefx/issues/5940#issuecomment-182107557
目前采用`Task.Run()`代替
- [x] Process.Start(string url);
.Net Core 默认`UseShellExecute=false`，所以打开URL时会抛出无法找到文件，参见：https://github.com/dotnet/corefx/wiki/ApiCompat#systemdiagnosticsprocess
- [x] `Assembly.GetExecutingAssembly().Location`或`Application.ExecutablePath`等方法获取的是`dll`路径
`Process.GetCurrentProcess().MainModule.FileName`可正确获取`exe`的路径
- [ ] 暂时无法设计 View
- [ ] 可能还有其他不同的 API

**Comment by HMBSbige** [comment]
本项目中所用到的 .NET Framework API 与 .Net Core 的不同：
- [x] string.GetHashCode();
.Net Core 因为防止哈希洪水攻击等安全原因默认启用随机 Hash 算法。
因本项目某些地方需要保证每次运行时Hash 值一样，所以目前已自实现`string.GetDeterministicHashCode();`
- [x] delegate.BeginInvoke();
.Net Core 编译时不报错，运行时抛出异常（PlatformNotSupported）,原因：https://github.com/dotnet/corefx/issues/5940#issuecomment-182107557
目前采用`Task.Run()`代替
- [x] Process.Start(string url);
.Net Core 默认`UseShellExecute=false`，所以打开URL时会抛出无法找到文件，参见：https://github.com/dotnet/corefx/wiki/ApiCompat#systemdiagnosticsprocess

还有可能有其他不同的 API

**Comment by HMBSbige** [comment]
目前 .Net Core 测试版本[下载](https://ci.appveyor.com/project/HMBSbige/shadowsocksr-windows/builds/24649073/artifacts)

**Comment by 1Gbps** [comment]
I think this is a good idea.

**Comment by wxlg1117** [comment]
好奇试了下,2012R2装了dotnet-runtime-2.1.11-win-x64.exe,运行程序没有任何反应,任务管理器里没有加载任何进程?

**Comment by HMBSbige** [comment]
> 好奇试了下,2012R2装了dotnet-runtime-2.1.11-win-x64.exe,运行程序没有任何反应,任务管理器里没有加载任何进程?

至少需要[.Net Core 3.0](https://dotnet.microsoft.com/download/dotnet-core/3.0)，我 Win7 虚拟机测试只装 runtime 运行会报错，装了SDK就好了，你可以试一下

**Comment by zly19540609** [comment]
I think this is a good idea.

**Comment by tmoonlight** [comment]
用standard写不行么，前端还是可以用winform/wpf的

**Comment by HMBSbige** [comment]
> 用standard写不行么，前端还是可以用winform/wpf的

这也是可行方案，类库完全可以用 standard 写，但主要讨论的是框架用的是 Framework 还是 Core

**Comment by TianMo-ZhangSan** [comment]
理论上，是不是也可以在linux环境运行了。Xamarin式跨平台

**Comment by HMBSbige** [comment]
> 理论上，是不是也可以在linux环境运行了。Xamarin式跨平台

微软说是只支持 Windows 桌面。我觉得理论上可行，但微软估计要改死了

**Comment by bbhxwl** [comment]
我以为你想移植服务端
