### ISSUE TITLE
退出ShadowsocksR程序会开启 自动检测设置

### ISSUE THREAD

**Issue by FreeGAV** [HMBSbige/ShadowsocksR-Windows#181]
退出ShadowsocksR程序会开启  系统代理的自动检测设置

自动检测设置 会导致浏览器启动时正在下载代理脚本而打开网页延迟

**Comment by Itzamana** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows/issues/70

我之前提到过，不过作者似乎就是这样设计的…

**Comment by HMBSbige** [comment]
因为这是微软的默认设置
