### ISSUE TITLE
如何让全局域名查询都走SSR的DNS配置？

### ISSUE THREAD

**Issue by LuohuaRain** [HMBSbige/ShadowsocksR-Windows#183]
规则是：绕过局域网和大陆，但我现在想让全部域名查询请求都能走SSR里的DNS设置。不知能否实现？谢谢

**Comment by zyOverture** [comment]
SSR的DNS设置和本地配置的DNS效果没有任何区别，还是说你想全部域名都进行远程解析？

**Comment by LuohuaRain** [comment]
> SSR的DNS设置和本地配置的DNS效果没有任何区别，还是说你想全部域名都进行远程解析？

对，全部域名都进行远程解析。或者
我看到SSR里的DNS可以设置DNS over TLS，所以我想让本机所有域名查询（不论大陆内外）都能走这个方案。

**Comment by zyOverture** [comment]
你可以自建一个纯净DNS，并且把它配置在SSR或者本地，最好能
全部远程解析不知道能不能实现，如果能实现也太不合理了，这样使你访问国内站点的时候也会解析成距离代理服务器较近的ip。

**Comment by huangxinrui** [comment]
请问官网地址是啥啊，我的订阅地址找不到了，麻烦给一下

**Comment by LuohuaRain** [comment]
@zyOverture 
因为我发现我这ISP污染严重，即使国内有些网站也被污染劫持了，所以冒出此想法。 感谢回复，我去试试。
