### ISSUE TITLE
[BUG]访问google时出错

### ISSUE THREAD

**Issue by AsadaYouko** [HMBSbige/ShadowsocksR-Windows#185]
**描述 bug**

访问google.com时会出错，其他网站例如google.com.hk就无此问题。

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 浏览器访问google

**预期行为**

正常访问

**截图**

无

**环境**

 - 系统：Windows 10 1903 18362.535
 - 浏览器：Chrome  79.0.3945.88
 - 程序版本：ShadowsocksR-net48-5.1.8.2
 
**其它内容**

[2019-12-31 15:26:32] [Info] Direct connect www.google.com:443
[2019-12-31 15:26:32] [Error] System.Net.Sockets.SocketException (0x80004005): 在其上下文中，该请求的地址无效。 0.0.0.0:443
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Service.Socks5Forwarder.Handler.ConnectCallback(IAsyncResult ar) 行号 375

**Comment by Neight99** [comment]
遇到过相同问题

**Comment by HMBSbige** [comment]
明显是 DNS 问题，用代理规则时也要搭配使用无污染的 DNS
