### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by d3wade412** [HMBSbige/ShadowsocksR-Windows#191]
win7企业版下   "ShadowsocksR-net48-5.1.8.2"  当小飞机在任务栏时，右键小飞机后出现的一排列表（如系统代理、规则代理、服务器、订阅……），当光标直到对应框时出现的下级列表（如指到系统代理时出现的直连、PAC、全局列表），所有出现在光标左边的下级列表都无法被选中

![QQ图片20200119012350](https://user-images.githubusercontent.com/59286551/72667830-eadc5f80-3a5a-11ea-8faf-c527fe66bd50.png)

如图，在图中当我光标划到  “规则设置”  弹出下级列表后，当我想往左移选取，下级列表就会自动消失，这个BUG 目前导致我无法更换服务器节点...

**Comment by HMBSbige** [comment]
系统问题
