### ISSUE TITLE
能增加对于shadowsocksr-native的支持吗

### ISSUE THREAD

**Issue by flowercoder** [HMBSbige/ShadowsocksR-Windows#194]
ShadowsocksR-Live/shadowsocksr-native
麻烦看下，简单来说就是ssr+websocket+tls
今年我这里ssr几乎一秒被看穿，这方法是我目前找到的最优解。
shadowsocks libev和v2ray+websocket+tls我也都试过了，但速度都很不理想。
shadowsocksr-native其核心也是走ssr端口的，希望有空能看下。

**Comment by HMBSbige** [comment]
No
