### ISSUE TITLE
[BUG]服务器统计界面，信息无法实时刷新

### ISSUE THREAD

**Issue by iDocomo** [HMBSbige/ShadowsocksR-Windows#196]
**描述 bug**
(选择负载均衡模式情况下）
服务器统计界面，选择其中一种排列方式，比如按照总下载量排列，按照本次下载量排列等等，统计数据发生变化以后，排列没有实时刷新。

之前4.9老版本是可以实时刷新排列的。

**截图**

![1](https://user-images.githubusercontent.com/60518959/73596356-64487780-455c-11ea-8281-5342a980f515.png)

![2](https://user-images.githubusercontent.com/60518959/73596373-978b0680-455c-11ea-8470-9edba808e2a1.png)

4.9版本效果
![GIF](https://user-images.githubusercontent.com/60518959/73596493-67903300-455d-11ea-9077-c25aa8899c2c.gif)

**环境**

 - 系统： Windows 10 
 - 浏览器： Chrome 80.0.3987.16
 - 程序版本： 5.1.8.3 Net Core x64

**Comment by HMBSbige** [comment]
PR welcome
