### ISSUE TITLE
[BUG]服务器列表中的数据不支持动态排序

### ISSUE THREAD

**Issue by 92PlayPUBG** [HMBSbige/ShadowsocksR-Windows#199]
**描述 bug**

服务器列表中的数据不支持动态排序

**如何复现**

1. 某一列部分字段有数据时排序
2. 这时候排序前没有数据的字段改变了，就不会自动排进来

**预期行为**

简要描述进行以上操作后预期的脚本行为

**截图**

[怎么贴图？我发到谷歌硬盘上，这是链接](https://drive.google.com/file/d/1fwnxI1i_MvtKzdq_jL3CMQQ1-4Il5NwS/view?usp=sharing)

**环境**

 - 系统：[Windows 7 x64]
 
 - 程序版本：ShadowsocksR-Portable-Win64-5.1.8.3.zip
 
**其它内容**
应该不需要日志吧？
当你需要看一堆节点的实时速度时，会被影响，原版ssr是可以动态排序的。

**Comment by HMBSbige** [comment]
Duplicate of #196
