### ISSUE TITLE
有兴趣加入开发交流吗

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#20]
tg来一个，邀请你哦，我们搞了一个go版的ssr后端。。。

**Comment by HMBSbige** [comment]
tg同名，不过我应该没什么时间

**Comment by Mr-Kwok** [comment]
SSRPanel还更新吗？

**Comment by bin008** [comment]
![Uploading DF00A196C5C286BFABF440D96628B962.png…]()
你好！这个问题怎么解决啊

**Comment by bin008** [comment]
# php artisan key:generate    你好！这个问题怎么解决啊

**Comment by bin008** [comment]
提示内存不够
