### ISSUE TITLE
[BUG]程序在后台时间长了以后，右击任务栏图标会卡很久才弹出菜单

### ISSUE THREAD

**Issue by Gauss5050** [HMBSbige/ShadowsocksR-Windows#201]
**描述 bug**

程序在后台时间长了以后，右击任务栏图标会卡很久才弹出菜单，有时需要多次点击才弹出菜单；另外，左键点击图标呼出主程序也有类似的卡顿表现。

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 中度使用电脑一段时间后，一般是一、两个小时以后
2. 似乎使用时间越长，卡的时间也越长

**预期行为**

右击任务栏图标后立即弹出菜单

**环境**

 - 系统：Windows 10 1909
 - 程序版本：5.1.8.3 .Net Core x64
 - 电脑：i5 3230m 8g DDR3

**Comment by Vstory** [comment]
同样问题，右击通知栏图标无响应

**Comment by Gauss5050** [comment]
> **描述 bug**
> 
> 程序在后台时间长了以后，右击任务栏图标会卡很久才弹出菜单，有时需要多次点击才弹出菜单；另外，左键点击图标呼出主程序也有类似的卡顿表现。
> 
> **如何复现**
> 
> 说明您在进行了怎样的操作后出现了bug：
> 
> 1. 中度使用电脑一段时间后，一般是一、两个小时以后
> 2. 似乎使用时间越长，卡的时间也越长
> 
> **预期行为**
> 
> 右击任务栏图标后立即弹出菜单
> 
> **环境**
> 
> * 系统：Windows 10 1909
> * 程序版本：5.1.8.3 .Net Core x64
> * 电脑：i5 3230m 8g DDR3

补充电脑使用情况：常常用Chrome打开超过30个标签页，一般不关闭，因此内存占用常常超过70%，怀疑可能和内存有关？别的程序，如火绒、坚果云等的任务栏图标右击也略有延迟，但不超过1秒。SSR的延迟有时体感超过3秒，越长时间没点击过图标，延迟的时间就越长。

**Comment by 2512821228** [comment]
可能是电脑性能问题吧，我从未出现过如上 BUG

**Comment by Gauss5050** [comment]
问题已经解决。原来是我之前将程序文件放在了机械硬盘中导致的，现在转移到固态硬盘以后响应速度已经恢复正常。
