### ISSUE TITLE
一个小小的文本错误

### ISSUE THREAD

**Issue by YoungSail** [HMBSbige/ShadowsocksR-Windows#204]
V5.1.8.3
端口设置中的目标地址下面应为目标端口
![image](https://user-images.githubusercontent.com/15042500/75103109-27d6db80-5631-11ea-96cb-38adf1b3d81a.png)

**Comment by HMBSbige** [comment]
已修复，可在 [Actions](https://github.com/HMBSbige/ShadowsocksR-Windows/actions) 中下载
