### ISSUE TITLE
[BUG]退出应用后没有关闭系统代理

### ISSUE THREAD

**Issue by 2512821228** [HMBSbige/ShadowsocksR-Windows#205]
在退出 ssr 应用后没有关闭系统代理（如下图所示）

![003](https://user-images.githubusercontent.com/11994295/75103542-d16c9b80-5636-11ea-86ab-5658233701f7.jpg)

**自动设置代理** 或 **手动设置代理** 的开关没有关

**如何复现**
这个 BUG 并非每次复现，在不退出 ssr 应用的状况下 **休眠系统** 有极大的概率复现

**环境**

 - 系统：Windows 10 1909 （2020.2.23 时，最新 Windows 版本）

**Comment by HMBSbige** [comment]
复现步骤不详细

**Comment by 2512821228** [comment]
**复现过程补充：**

1. 保持 ssr 正常运行
2. 将 Windows 睡眠，等待一段时间（睡眠时间越长，BUG 复现概率越大）
![image](https://user-images.githubusercontent.com/11994295/75104994-b3a93180-564a-11ea-8919-0fc734e409c5.png)
3. 启动 Windows
4. 退出 ssr

经过如何上步奏，有大概率复现 BUG
