### ISSUE TITLE
[BUG]打开www.google.com报错：ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by KartNid** [HMBSbige/ShadowsocksR-Windows#206]
**描述 bug**

启用该程序后（无论pac模式还是全局）用任何浏览器打开www.google.com会报错

> 此网站无法提供安全连接www.google.com
 发送的响应无效。
ERR_SSL_PROTOCOL_ERROR

**如何复现**
下载以后将gfwlist更新为最新，开启pac模式。
打开www.google.com就会报错，之后尝试了一下全局模式也会报错。
然后我尝试了google.co.jp和google.co.hk，可以正常打开。只有.com会报错。
最后我关闭该程序，而用相同的代理服务器通过sstap代理，就可以正常打开www.google.com了。可以排除是代理服务器本身的问题。

**预期行为**

可以正常打开google.com

**环境**

 - 系统：Windows 10 1909
 - 浏览器：chrome 78、edge beta（chromium内核）、firefox 73
 - 程序版本：v5.1.8.3

**Comment by HMBSbige** [comment]
你代理规则是不是没选全局

**Comment by KartNid** [comment]
> 你代理规则是不是没选全局

我选了的
