### ISSUE TITLE
[BUG]訂閱設置時將網址和訂閱備註填反了會導致無限彈更新訂閱失敗

### ISSUE THREAD

**Issue by BigTear** [HMBSbige/ShadowsocksR-Windows#209]
**描述 bug**

訂閱設置時將網址和訂閱備註填反了會導致無限彈更新訂閱失敗的消息，程式會卡死，需要重啟程式並直接刪除錯誤的服務器訂閱才能恢復正常。

**环境**

 - 系统：[Windows 10 1909 Edu]
 - 程序版本：[ShadowsocksR-net48-5.1.3.4.zip]

一直用的舊版，不知新版本程式該bug是否已修補

**Comment by HMBSbige** [comment]
请认真填写环境
