### ISSUE TITLE
最新665dd49代码 编译环境 该怎么配置?

### ISSUE THREAD

**Issue by wxlg1117** [HMBSbige/ShadowsocksR-Windows#21]
有安装dotnet-sdk-3.0.100-preview5-011568-win-x64.exe,vsc也启用了"使用.NET Core SDK预览版"

但是VSC加载项目就报错:
C:\Users\Administrator\Desktop\ShadowsocksR-Windows-by-HMBSbige\shadowsocks-csharp\shadowsocksr.csproj : error  : 项目系统打不开项目文件，因为该文件缺少一些关键导入或找不到引用的 SDK。

详细信息:
无法找到 .NET Core SDK。请检查确保已安装此项且 global.json 中指定的版本(如有)与所安装的版本相匹配。

PS:另外一个虚拟机环境里面,安装了dotnet-sdk-2.1.700-win-x64.exe,然后折腾了又报另外一个错误"

C:\Users\Administrator\Documents\ShadowsocksR-Windows-by-HMBSbige\shadowsocks-csharp\shadowsocksr.csproj : error  : 项目系统打不开项目文件，因为该文件缺少一些关键导入或找不到引用的 SDK。

详细信息:
C:\Program Files\dotnet\sdk\2.1.700\Sdks\Microsoft.NET.Sdk.WindowsDesktop\Sdk未找到。检查是否安装了最新的. net Core SDK，或增加global.json中指定的版本。

大佬指点一下

**Comment by HMBSbige** [comment]
vs是2019吗？

**Comment by HMBSbige** [comment]
顺便说一下，根目录的`build.cmd`是用来编译的

**Comment by wxlg1117** [comment]
@HMBSbige ,对啊,VSC是16.0.3，现在的情况是VSC根本无法加载项目

**Comment by HMBSbige** [comment]
> @HMBSbige ,对啊,VSC是16.0.3，现在的情况是VSC根本无法加载项目，加载就报那个错.

是 vs 吧，而且现在vs2019已经 16.1.1了

**Comment by HMBSbige** [comment]
建议重新 pull ，要么删除`obj`文件夹试试
顺便问下`dotnet --version`是多少，我的是`3.0.100-preview5-01156`

**Comment by wxlg1117** [comment]
![Snipaste_2019-05-28_21-57-56](https://user-images.githubusercontent.com/9752596/58483911-af231b80-8193-11e9-8f40-8555ec72e6d7.png)


C:\Users\Administrator>dotnet --version
3.0.100-preview5-011568

**Comment by HMBSbige** [comment]
我用另一台电脑git clone，安装.Net Core 3.0 VS2019升级到16.1.1，能正常加载
![image](https://user-images.githubusercontent.com/19153265/58484874-88fe7b00-8195-11e9-803e-67e097819296.png)

**Comment by HMBSbige** [comment]
还有问题的话，截下图吧

**Comment by wxlg1117** [comment]
2kr2虚拟机快照返回纯净安装时,然后新安装16.1.1版本后终于正常了...另外求问下怎么编译为 .net 4.7.2的解决方案? 系统已经安装了4.7.2的SDK但是这个项目属性的下拉列表里面没有出现...自己新建项目倒是有的
![Snipaste_2019-05-29_21-43-48](https://user-images.githubusercontent.com/9752596/58532453-2f8b6000-8218-11e9-9328-164865331e9b.png)

**Comment by HMBSbige** [comment]
根目录有`build.cmd`，用来编译所有版本的

**Comment by wxlg1117** [comment]
C:\Users\Administrator\Documents\ShadowsocksR-Windows>build.cmd
dotnet SDK version
3.0.100-preview5-011568
Building .NET Core
'msbuild' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by HMBSbige** [comment]
用`Developer Command Prompt for VS 2019`啊，开始菜单里有

**Comment by wxlg1117** [comment]
感谢大佬,都OK了

**Comment by wxlg1117** [comment]
Release文件夹 PATH 列表
├─net48
│      ShadowsocksR.exe
│      ShadowsocksR.exe.config
│      ShadowsocksR.pdb
│      
└─netcoreapp3.0
    │  ShadowsocksR.deps.json
    │  ShadowsocksR.dll
    │  ShadowsocksR.exe
    │  ShadowsocksR.pdb
    │  ShadowsocksR.runtimeconfig.dev.json
    │  ShadowsocksR.runtimeconfig.json
    │  
    ├─publish
    │      DnsClient.dll
    │      Newtonsoft.Json.dll
    │      ShadowsocksR.deps.json
    │      ShadowsocksR.dll
    │      ShadowsocksR.exe
    │      ShadowsocksR.pdb
    │      ShadowsocksR.runtimeconfig.json
    │      zxing.dll
    │      ZXing.Windows.Compatibility.dll
    │      
    ├─win-x64
    │  │  Accessibility.dll
    │  │  api-ms-win-core-console-l1-1-0.dll
    │  │  api-ms-win-core-datetime-l1-1-0.dll
    │  │  ......
    │  │  ShadowsocksR.deps.json
    │  │  ShadowsocksR.dll
    │  │  ShadowsocksR.exe
    │  │  ShadowsocksR.pdb
    │  │  ShadowsocksR.runtimeconfig.dev.json
    │  │  ShadowsocksR.runtimeconfig.json
    │  │  sos.dll
    │  │  ......
    │  │  wpfgfx_cor3.dll
    │  │  zxing.dll
    │  │  ZXing.Windows.Compatibility.dll
    │  │  
    │  └─publish
    │          ShadowsocksR.exe
    │          ShadowsocksR.pdb
    │          
    └─win-x86
        │  Accessibility.dll
        │  api-ms-win-core-console-l1-1-0.dll
        │  api-ms-win-core-datetime-l1-1-0.dll
        │  ......
        │  ShadowsocksR.deps.json
        │  ShadowsocksR.dll
        │  ShadowsocksR.exe
        │  ShadowsocksR.pdb
        │  ShadowsocksR.runtimeconfig.dev.json
        │  ShadowsocksR.runtimeconfig.json
        │  sos.dll
        │  SOS.NETCore.dll
        │  sos_x86_x86_4.6.27622.75.dll
        │  ......
        │  zxing.dll
        │  ZXing.Windows.Compatibility.dll
        │  
        └─publish
                ShadowsocksR.exe
                ShadowsocksR.pdb
                

@HMBSbige 大佬,能大概说明下netcoreapp3.0目录下几个目录有什么区别么?
publish
win-x64
win-x64\publish
win-x86
win-x86\publish

比如我的机器要用.net 3.0的,那我只需要复制:
└─netcoreapp3.0
    │  ShadowsocksR.deps.json
    │  ShadowsocksR.dll
    │  ShadowsocksR.exe
    │  ShadowsocksR.pdb
    │  ShadowsocksR.runtimeconfig.dev.json
    │  ShadowsocksR.runtimeconfig.json
还是说netcoreapp3.0下整个目录以及子目录里的文件都需要?

**Comment by HMBSbige** [comment]
publish文件夹下面的就是发布文件，.Net Core 3.0 三个版本不同可以看一下 README
