### ISSUE TITLE
能否增加 China DNS 功能，兼容PAC模式

### ISSUE THREAD

**Issue by willbeevil** [HMBSbige/ShadowsocksR-Windows#210]
能否实现类似 SSR for Android 的 China DNS 功能，且兼容PAC模式
![image](https://user-images.githubusercontent.com/56044407/75609101-cb981e00-5b40-11ea-8d03-49994a434504.png)
就这种直接无脑填进去就行的

**需求：PAC模式下，代理时使用DNS，直连时使用China DNS**
——————————————
目前我的DNS设置
![image](https://user-images.githubusercontent.com/56044407/75609126-f6827200-5b40-11ea-9dee-397a6d0af65c.png)

此设置下，对DNS服务器进行测试
测试网站 https://whoer.net/ https://www.expressvpn.com/dns-leak-test

PAC模式下DNS测试结果为China DNS
全局模式下DNS测试结果为外网DNS
（代理规则设置为全局或绕过局域网和大陆不影响以上测试结果

**这是否说明PAC模式下进行代理的时候没有调用设置的DNS服务器**

我不太明白这里的DNS设置是如何工作的，
也许目前通过设置能达到需求效果，但我设置错了？请大佬指教

**Comment by zyOverture** [comment]
看[这个](https://github.com/HMBSbige/ShadowsocksR-Windows/wiki/代理模式-和-代理规则) ，帮助理解

**Comment by willbeevil** [comment]
> 看[这个](https://github.com/HMBSbige/ShadowsocksR-Windows/wiki/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F-%E5%92%8C-%E4%BB%A3%E7%90%86%E8%A7%84%E5%88%99) ，帮助理解

这张图我看明白了，可是DNS是位于哪一阶段的，我不明白为什么PAC模式下和全局模式下的代理会产生不一样的DNS结果
