### ISSUE TITLE
[BUG]5.1.8.3 统计窗口无法自动调整大小的问题

### ISSUE THREAD

**Issue by kidsoyo** [HMBSbige/ShadowsocksR-Windows#213]
版本号 ShadowsocksR-net48-5.1.8.3
操作系统 win10 1809
问题：统计窗口无法调整窗口，见下图
![image](https://user-images.githubusercontent.com/35915585/75880131-a87ab080-5e57-11ea-9578-7b3dc0fe8fbd.png)

1.自动调整窗口大小按钮点击无效
2.手动调整后，重新打开依旧恢复为上图状态

**Comment by HMBSbige** [comment]
@kidsoyo 系统分辨率？

**Comment by kidsoyo** [comment]
> @kidsoyo 系统分辨率？

1920*1080

**Comment by HMBSbige** [comment]
那估计是自己系统问题

**Comment by kidsoyo** [comment]
> 那估计是自己系统问题

感谢回复，自己研究了下，开启了mactype渲染造成的，排除此进程后正常
