### ISSUE TITLE
无法转发dns请求到远程服务器

### ISSUE THREAD

**Issue by Brightmbsh** [HMBSbige/ShadowsocksR-Windows#22]
您好，此版本ssr经过测试，貌似无法转发dns查询请求到远程服务器，所有的dns查询都使用的是本地dns服务器，国内dns污染严重，这样对使用影响很大，能否解决下？多谢了

**Comment by HMBSbige** [comment]
不受dns污染影响，本地dns请求只是用于自定义规则

如有问题，请详细说明如何复现

**Comment by Brightmbsh** [comment]
您好，使用DnscryptProxy做本地dns服务器时，ssr无论是pac还是全局模式，DnscryptProxy均会记录到使用本地dns服务器查询请求的记录，显然没有使用代理服务器做dns解析，使用ss最新版则没有这个问题

**Comment by HMBSbige** [comment]
就这是ssr和ss的最大不同吧，ssr的feature，本地dns请求用于代理规则判断，若判断是远程的话还是会做远程解析的

**Comment by Brightmbsh** [comment]
原来是这样，十分感谢！但是这样会不会有隐私方面的问题啊😯

Bruce Wayne <notifications@github.com> 于 2019年6月8日周六 上午2:33写道：

**Comment by HMBSbige** [comment]
我觉得无所谓，你觉得不安全可以自己设啊，选项设置里有
