### ISSUE TITLE
账号被禁

### ISSUE THREAD

**Issue by LP123k** [HMBSbige/ShadowsocksR-Windows#224]
被管理员禁用了账户

**Comment by LP123k** [comment]
416029




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HMBSbige-RBQ"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 上午10:33
收件人:&nbsp;"HMBSbige/ShadowsocksR-Windows"<ShadowsocksR-Windows@noreply.github.com&gt;;
抄送:&nbsp;"海久"<1638697794@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HMBSbige/ShadowsocksR-Windows] 账号被禁 (#224)





 
Closed #224.

**Comment by HMBSbige-RBQ** [comment]
您好，服务商提供本客户端下载并不代表者我方涉及任何节点问题。请自行联系节点服务提供商。

**Comment by LP123k** [comment]
怎么联系

**Comment by LP123k** [comment]
请问怎么联系管理员？

**Comment by HMBSbige-RBQ** [comment]
这不是我方应该解决的问题，更不是我方有能力解决的问题
