### ISSUE TITLE
[BUG]订阅当中的链接以空格分割时只识别第一个

### ISSUE THREAD

**Issue by hs180-cn** [HMBSbige/ShadowsocksR-Windows#225]
ssr更新订阅只能获取到其中一条，服务器列表无法获取全。

**Comment by HMBSbige-RBQ** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows/issues/224#issuecomment-606366309

**Comment by hs180-cn** [comment]
同样的订阅链接原版SSR不存在该问题。测试订阅地址：https://ncuc.xyz/link/9tlf4UyhdcpZzarq?mu=1

**Comment by hs180-cn** [comment]
我个人觉得会不会是换行兼容性问题导致？

**Comment by HMBSbige-RBQ** [comment]
@HMBSbige-RBQ

**Comment by HMBSbige-RBQ** [comment]
[9tlf4UyhdcpZzarq.txt](https://github.com/HMBSbige/ShadowsocksR-Windows/files/4441657/9tlf4UyhdcpZzarq.txt)

该订阅使用空格而非换行符分割多个节点地址，我不确定 @HMBSbige 是否愿意兼容这种非标准格式

**Comment by HMBSbige-RBQ** [comment]
经讨论，我方不会处理。请自行联系服务提供商。本issue存档供日后参考，感谢提出。

**Comment by hs180-cn** [comment]
好的，感谢。建议日后有空增加兼容性，毕竟同样的订阅链接原版以及路由器还有安卓客户端都能兼容使用。
