### ISSUE TITLE
更新订阅后能默认连第一个节点吗

### ISSUE THREAD

**Issue by suhuaixing** [HMBSbige/ShadowsocksR-Windows#227]
以前倒序排的时候，默认倒数第一个，刚好两个都倒了。
上一版本把倒序修了，但是仍然连倒数第一个，就有点儿尴尬了，最后的节点在很后面，我往下划才发现自己连错了..

**Comment by HMBSbige-RBQ** [comment]
![image](https://user-images.githubusercontent.com/62918438/78848583-b8128980-7a01-11ea-9c4f-36e1cb4d2dc4.png)
