### ISSUE TITLE
订阅获取的节点，分组名称错误

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#23]
分组名称 无法获取每个节点的分组名称，每次都是把分组名称只取了第一个节点的分组名称。

如图所示：
![QQ图片20190613151626.png](https://i.loli.net/2019/06/13/5d01f85d73d9443411.png)

PS：由于你的隐私设置，我无法把你加入到tg群组。。

**Comment by HMBSbige** [comment]
改好了：![](https://user-images.githubusercontent.com/19153265/59419052-b76a9000-8dfc-11e9-946b-6d63985a41c5.png)

关于 BUG 能详细描述一下吗？

**Comment by HMBSbige** [comment]
难道你想说是一个订阅地址多个分组？
根据[文档](https://github.com/HMBSbige/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3)一个订阅地址只能对应一个分组
建议还是写到备注里，或者一个组一个订阅地址

**Comment by ssrpanel** [comment]
> 难道你想说是一个订阅地址多个分组？
> 根据[文档](https://github.com/HMBSbige/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3)一个订阅地址只能对应一个分组
> 建议还是写到备注里，或者一个组一个订阅地址

那样不科学呀。一个订阅地址中可能不同的节点来自不同的分组，比如:
分组有：
 香港节点 - HK1
 香港节点 - HK2
 香港节点 - HK3
 美国节点 - US1
 美国节点 - US2
 日本节点 - JP1

酱紫。。而且如果有多个订阅地址，建议最开始应以订阅的备注名为开头，例如：
客户端添加了两个订阅连接，其各自的备注名为：
订阅连接1，备注名：XXXCLOUD
订阅连接2，备注名：ABCCLOUD
那么 订阅更新时，节点列表应为：
XXXCLOUD -  香港节点 - HK1
XXXCLOUD -  香港节点 - HK2
XXXCLOUD -   香港节点 - HK3
XXXCLOUD -  美国节点 - US1
XXXCLOUD -  美国节点 - US2
XXXCLOUD -  日本节点 - JP1
ABCCLOUD -  日本节点 - JP1
ABCCLOUD -  美国节点 - US1
ABCCLOUD -  美国节点 - US2

**Comment by ssrpanel** [comment]
还有，后面的连接 其实可以不显示的，太糙了，或者做判断，如果 节点没有备注名，则显示服务器IP，如果有备注名，则显示备注名不显示 后面的域名，举例说明：
XXXCLOUD - 香港节点 - HK1（*.xxx.com:1111）  ----> 可以改为： XXXCLOUD - 香港节点 - HK1

**Comment by HMBSbige** [comment]
> 还有，后面的连接 其实可以不显示的，太糙了，或者做判断，如果 节点没有备注名，则显示服务器IP，如果有备注名，则显示备注名不显示 后面的域名，举例说明：
> XXXCLOUD - 香港节点 - HK1（*.xxx.com:1111） ----> 可以改为： XXXCLOUD - 香港节点 - HK1

friendly name 这种确实有计划要改，最近改界面的时候顺便改一下

**Comment by HMBSbige** [comment]
> > 难道你想说是一个订阅地址多个分组？
> > 根据[文档](https://github.com/HMBSbige/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3)一个订阅地址只能对应一个分组
> > 建议还是写到备注里，或者一个组一个订阅地址
> 
> 那样不科学呀。一个订阅地址中可能不同的节点来自不同的分组，比如:
> 分组有：
> 香港节点 - HK1
> 香港节点 - HK2
> 香港节点 - HK3
> 美国节点 - US1
> 美国节点 - US2
> 日本节点 - JP1
> 
> 酱紫。。而且如果有多个订阅地址，建议最开始应以订阅的备注名为开头，例如：
> 客户端添加了两个订阅连接，其各自的备注名为：
> 订阅连接1，备注名：XXXCLOUD
> 订阅连接2，备注名：ABCCLOUD
> 那么 订阅更新时，节点列表应为：
> XXXCLOUD - 香港节点 - HK1
> XXXCLOUD - 香港节点 - HK2
> XXXCLOUD - 香港节点 - HK3
> XXXCLOUD - 美国节点 - US1
> XXXCLOUD - 美国节点 - US2
> XXXCLOUD - 日本节点 - JP1
> ABCCLOUD - 日本节点 - JP1
> ABCCLOUD - 美国节点 - US1
> ABCCLOUD - 美国节点 - US2

一个订阅一个组主要涉及更新订阅算法等，改成对应多个组涉及代码太多了，而且原来的订阅代码很乱

计划放在下下个版本更新

**Comment by HMBSbige** [comment]
> 客户端添加了两个订阅连接，其各自的备注名为：

是增加一个自定义备注的意思吗？专门备注订阅链接？

因为原来一个订阅对应一个组，组名相当于备注了属于哪个订阅链接

**Comment by ssrpanel** [comment]
期待ing

**Comment by ssrpanel** [comment]
嗯，破娃之前这个 C# 版本这个订阅应该是早期雏形，SSRR 那儿也一直没解决，我看了代码确实要大重构这部分代码。。。因为我不精通C#，故....厚着脸皮来你这儿提 enhancement
