### ISSUE TITLE
订阅接口文档[BUG]

### ISSUE THREAD

**Issue by lipaopao000** [HMBSbige/ShadowsocksR-Windows#234]
**描述 bug**

更新win客户端到v5.1.8.6后，无法更新订阅，手动批量导入也不行。
我的订阅文档是以空格来分割每个SSR链接，一行有多个节点。
能不能兼容一下？

**预期行为**
能导入以空格来分隔的批量链接。

**环境**

 - 系统：[如 Windows 10 1909]
 - 程序版本：v5.1.8.6

**Comment by HMBSbige** [comment]
Duplicate of #225

**Comment by lipaopao000** [comment]
v5.1.8.3版本测试没问题
