### ISSUE TITLE
v5.1.9 Release 遗漏了 ShadowsocksR-net48-5.1.9.zip

### ISSUE THREAD

**Issue by Measureless** [HMBSbige/ShadowsocksR-Windows#235]
缺少 ShadowsocksR-net48-5.1.9.zip
![image](https://user-images.githubusercontent.com/30423783/79897972-092c6f80-843d-11ea-9ffe-71dc28306e8f.png)

**Comment by LeoJeson** [comment]
确实，没有net48我都不知道怎么更新了，还是说作者大大不想出这个版本了

**Comment by huxim** [comment]
其实一开始是有的,估计有问题撤下了吧

**Comment by HMBSbige** [comment]
已修复(
