### ISSUE TITLE
[BUG]5.1.9订阅更新不完整！

### ISSUE THREAD

**Issue by pushuangchang** [HMBSbige/ShadowsocksR-Windows#236]
**描述 bug**

更新SSR 5.1.9 后订阅更新不完整，订阅地址只更新到流量信息，节点信息消失

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 更新SSR到5.1.9
2. 使用爬墙云的订阅信息
3. 更新订阅

**预期行为**

SSR的 服务器 选项卡 显示所有节点

**截图**

如果可以，请添加屏幕截图以帮助解释您的问题
![批注 2020-04-22 032922](https://user-images.githubusercontent.com/29980586/79905870-80680080-8449-11ea-8ce8-738cad832b39.png)

**环境**

 - 系统：Windows 10 1909
 - 浏览器：无关
 - 程序版本：5.1.9 net48
 
**其它内容**

在此添加有关此问题的任何其它内容。
最好能贴上相关的日志

**Comment by HMBSbige-RBQ** [comment]
dup of #225
