### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YonlynWu** [HMBSbige/ShadowsocksR-Windows#239]
**描述 bug**

禁用节点后自动取消禁用

**如何复现**

我禁用了前四个节点，隔一段时间就自动取消第一个节点的禁用

 - 系统：Windows 10 1909
 - 浏览器：Chrome  81.0.4044.122
 - 程序版本：ShadowsocksR-net48-5.1.9

**Comment by HMBSbige** [comment]
Duplicate of #138
