### ISSUE TITLE
4K分辨率下文字变糊

### ISSUE THREAD

**Issue by CaesarTheFox** [HMBSbige/ShadowsocksR-Windows#24]
今天刚用了4.9.5.1，和4.9.1相比， 似乎文字变糊了，我的分辨率是3840 x 2160 pixels。
标题栏服务器记录几个字明显要比下方的文字清晰锐利。
之前用4.9.1没有这个问题，有点奇怪。
![4~E )8R5Z 1XO%NI3@}UBI](https://user-images.githubusercontent.com/46268648/59457903-441f4900-8e11-11e9-957e-d04d139630d5.png)

**Comment by HMBSbige** [comment]
正在转 WPF，先把界面全重新设计了，高 DPI 的问题就能解决了，不要急

**Comment by HMBSbige** [comment]
[5.0.0.0](https://github.com/HMBSbige/ShadowsocksR-Windows/releases/tag/5.0.0.0) 版本全是WPF窗口应该没问题了
