### ISSUE TITLE
[BUG]无法正常加载项目

### ISSUE THREAD

**Issue by williamszey** [HMBSbige/ShadowsocksR-Windows#240]
**描述 bug**

vs打开源码后 出现shadowsocksr 项目加载失败

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 打开vs后，无法加载shadowsocksr，重新加载后提示 项目文件不完整。缺少预期导入。
2. 
3. 

**预期行为**

正常打开项目

**截图**

如果可以，请添加屏幕截图以帮助解释您的问题

**环境**

 - 系统：[如 Windows 10 1809]
 - 浏览器：[如 Chrome 74.0.3729.157，无关则删除]
 - 程序版本：[如 5.0.0.0 .Net Core SelfContained x64]
 
**其它内容**

在此添加有关此问题的任何其它内容。
最好能贴上相关的日志

**Comment by AmazingDM** [comment]
@williamszey 建议百度(

**Comment by guilin1iu** [comment]
我尝试使用VisualStudio 2019打开也是无法运行，貌似是ARSoft.Tools.Net这一个程序包最高只有2.29版本，并没有2.30
![image](https://user-images.githubusercontent.com/58240137/80495966-29a77d00-899b-11ea-8d4a-e6de4c93166a.png)
下载2.29版本之后，发现少了此命名空间
![image](https://user-images.githubusercontent.com/58240137/80496067-45128800-899b-11ea-9274-f2a3648e7d0c.png)

**Comment by HMBSbige** [comment]
Duplicate of #162

**Comment by guilin1iu** [comment]
非常感谢您的解答
