### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sam-Caesarmat** [HMBSbige/ShadowsocksR-Windows#241]
**描述 bug**

在部分win7系统使用时，一级菜单与二级菜单之间距离相差较大，导致在移动鼠标经过两级菜单交界选择节点时，第二级自动消失。

**截图**
![image](https://user-images.githubusercontent.com/42537544/80510864-e4407b00-89ad-11ea-8f86-2801e389de78.png)

**环境**

 - 系统：[Windows 7 旗舰版]
 - 程序版本：[Windows 7_SP1_2014_X1]

**Comment by HMBSbige** [comment]
Duplicate of #191
