### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hhg999** [HMBSbige/ShadowsocksR-Windows#242]
安装了.net 5.0，照理说高于4.8，为何SSR-net4.8版不认？

**Comment by HMBSbige** [comment]
@hhg999

**Comment by HMBSbige** [comment]
.NET 5 = .NET Core vNext

.NET 5 都还没有正式版，一般用户就不要装了吧

**Comment by hhg999** [comment]
还有，HMBSbige版没有查找并删除重复节点的功能，v2ray就有这项功能，不过，v2ray的此项功能也不完善：重复节点可以导入。总之，建议开发两项功能：1、查找并删除重复节点；2、导入重复节点时提示&ldquo;节点重复&rdquo;。

**Comment by hhg999** [comment]
还有，HMBSbige版没有查找并删除重复节点的功能，v2ray有此功能，不过，v2ray的此项功能也不完善：重复节点可以导入。总之，建议开发新功能：1，查找并删除重复节点； 2，导入重复节点时提示&ldquo;节点重复&rdquo;。

**Comment by hhg999** [comment]
还有一个建议：添加新节点之后（无论是二维码扫入，还是粘贴板导入或者其它方式添加），1、提示新添加的节点数量；2、新添加的节点闪烁或者高亮显示，以提示用户：新添加的节点在哪个组别，便于用户修改别名或者其它信息。目前的版本，添加节点之后，根本就不知道新添加的节点添加成功否，被添加到了何处。
