### ISSUE TITLE
一个不算bug的bug?

### ISSUE THREAD

**Issue by wxlg1117** [HMBSbige/ShadowsocksR-Windows#25]
![QQ截图20190614104758](https://user-images.githubusercontent.com/9752596/59480186-39f15f00-8e92-11e9-8782-4f721dcc9abc.jpg)

![QQ截图20190614104752](https://user-images.githubusercontent.com/9752596/59480188-3d84e600-8e92-11e9-92e4-33e6d1dfd3ff.jpg)

大佬,界面风格有点不统一啊? 
另外一直没明白那个递归DNS填空项是什么意思?和DNS是什么关系?

**Comment by HMBSbige** [comment]
界面风格：https://github.com/HMBSbige/ShadowsocksR-Windows/issues/24#issuecomment-501960132

递归 DNS 用于解析节点是域名的

DNS 解析出来用于判断“代理规则”的

**Comment by wxlg1117** [comment]
明白了,那解析浏览器之类请求发来的域名的dns在哪设置的?

**Comment by HMBSbige** [comment]
> 明白了,那解析浏览器之类请求发来的域名的dns在哪设置的?

就是上面那个 DNS 啊...

**Comment by HMBSbige** [comment]
Update to 5.0.0.0
