### ISSUE TITLE
能否增加可用性和速率记录并自动标记并停用?

### ISSUE THREAD

**Issue by fjxhkj** [HMBSbige/ShadowsocksR-Windows#26]
能否增加类似SSCap的节点检测功能?然后把检查结果保存到gui-config.json里.最好是能够自动停用暂时不可用的节点.
因为用rss添加的节点一下子一大堆,也没有很好的工具检查这些节点的可用性,而SSCap就有类似的功能,但比较简陋.

**Comment by HMBSbige** [comment]
正在设计的是自动检测是否可用并禁用不可用的，我觉得没必要保存结果，因为本来就有个记录节点开关的参数

**Comment by HMBSbige** [comment]
[5.0.0.0](https://github.com/HMBSbige/ShadowsocksR-Windows/releases/tag/5.0.0.0) 版本有个很傻的功能，但是不推荐使用。
推荐用 [SSRSpeed](https://github.com/NyanChanMeow/SSRSpeed)
