### ISSUE TITLE
打开服务器记录窗口不能直接定位到已选中的服务器，并且窗口老是自动回到默认大小。

### ISSUE THREAD

**Issue by ufo1024k** [HMBSbige/ShadowsocksR-Windows#28]
鼠标中键点击图标打开服务器记录窗口后，不能快速定位已选中的服务器，服务器多的话，要用鼠标拖动找，这样很麻烦，试了下老版本倒是可以快速定位。
再有就是此窗口重新打开后不能保存以前自定义设置的窗口大小

**Comment by HMBSbige** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows/releases/download/5.0.0.0/ShadowsocksR-net48-5.0.0.1.zip

**Comment by ufo1024k** [comment]
> https://github.com/HMBSbige/ShadowsocksR-Windows/releases/download/5.0.0.0/ShadowsocksR-net48-5.0.0.1.zip

谢谢大佬，问题已经完美解决！
