### ISSUE TITLE
不明白？用这种SSR的人似乎比较少，用另一种的则似乎多不少。

### ISSUE THREAD

**Issue by hdshuai** [HMBSbige/ShadowsocksR-Windows#29]
ShadowsocksR for Windows目前能搜到的有两种，另一种是https://github.com/shadowsocksrr/shadowsocksr-csharp 。

目前用shadowsocksr-csharp的人似乎更多。

不知道，这两种有什么区别？

**Comment by HMBSbige** [comment]
看不懂你在说什么

**Comment by hdshuai** [comment]
> 看不懂你在说什么

还有一种ssr,https://github.com/shadowsocksrr/shadowsocksr-csharp

**Comment by HMBSbige** [comment]
我这主要是自用的，看到bug就修，看到不爽就改
