### ISSUE TITLE
建议“服务器负载均衡”移到主菜单。

### ISSUE THREAD

**Issue by hdshuai** [HMBSbige/ShadowsocksR-Windows#30]
建议“服务器负载均衡”移到主菜单。因为这一项经常变换。

**Comment by HMBSbige** [comment]
放在哪一行，我感觉都挺不合适的

**Comment by hdshuai** [comment]
![IMG_2019](https://user-images.githubusercontent.com/42534549/60755383-8e1ad980-a021-11e9-800b-9d85c7a515aa.jpg)

**Comment by HMBSbige** [comment]
容我拒绝。正常使用是不会经常切换的，而且就多一步。还是不改回去了
