### ISSUE TITLE
选节点可以用滚轮

### ISSUE THREAD

**Issue by nameless3721** [HMBSbige/ShadowsocksR-Windows#32]
选节点列表太长的话希望可以直接用滚轮来移动
![无标题](https://user-images.githubusercontent.com/50364156/60964984-a6effb80-a34f-11e9-917d-4273289fee27.png)

**Comment by HMBSbige** [comment]
其实推荐在“服务器记录”窗口选节点，这样明显更快

**Comment by nameless3721** [comment]
> 其實推薦在“服務器記錄”窗口選節點，這樣明顯更快
> 
> 按Ctrl +鼠標左鍵或者鼠標中鍵點擊圖標就可以打開“服務器記錄”窗口了

好的 学到了 谢谢
