### ISSUE TITLE
恢复双击编辑服务器的功能

### ISSUE THREAD

**Issue by roshad** [HMBSbige/ShadowsocksR-Windows#33]
5.0在服务器记录窗口双击服务器打开编辑服务器窗口的功能没了。
我经常用这个功能自不同服务商提供的节点中筛选较好用的，组成自己的节电池。
实现起来应该比较简单，建议恢复。

**Comment by HMBSbige** [comment]
双击前面的`ID`那一列

之前双击服务器那列容易和单击产生冲突，我觉得设计不合理就去掉了
