### ISSUE TITLE
[BUG]不算什么bug，5.0.0.1版本更新订阅之后节点的顺序会混乱

### ISSUE THREAD

**Issue by tesla4321** [HMBSbige/ShadowsocksR-Windows#34]
**描述 bug**

5.0.0.1版本更新订阅之后节点的顺序会混乱

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 点击更新SSR服务器订阅（不通过代理）

**环境**

 - 系统：[如 Windows 10 1903]
 - 程序版本：5.0.0.1

**Comment by HMBSbige** [comment]
其实是 BUG，等待下版本重写订阅更新算法

**Comment by hyy34** [comment]
5.0.0.1在哪下载的？请老大给个讨论组，找到组织

**Comment by HMBSbige** [comment]
> 5.0.0.1在哪下载的？请老大给个tg讨论组，找到组织

https://github.com/HMBSbige/ShadowsocksR-Windows/releases/tag/5.0.0.0

放在 5.0.0.0 下了

**Comment by hyy34** [comment]
> > 5.0.0.1在哪下载的？请老大给个tg讨论组，找到组织
> 
> https://github.com/HMBSbige/ShadowsocksR-Windows/releases/tag/5.0.0.0
> 
> 放在 5.0.0.0 下了

请问5.0.01更新了点啥？

**Comment by HMBSbige** [comment]
> > > 5.0.0.1在哪下载的？请老大给个tg讨论组，找到组织
> > 
> > 
> > [`5.0.0.0` (release)](https://github.com/HMBSbige/ShadowsocksR-Windows/releases/tag/5.0.0.0)
> > 放在 5.0.0.0 下了
> 
> 请问5.0.01更新了点啥？

https://github.com/HMBSbige/ShadowsocksR-Windows/issues/28
