### ISSUE TITLE
使用auth_akarin_rand协议和tls1.2_ticket_auth混淆后内存一直只涨不降

### ISSUE THREAD

**Issue by Filterrr** [HMBSbige/ShadowsocksR-Windows#37]
描述错误

5.0.0.1版本更新订阅之后节点的顺序会混乱

如何复现

说明您在进行了怎样的操作后出现了错误：

1.使用auth_akarin_rand协议和tls1.2_ticket_auth混淆后内存一直只涨不降
![1](https://user-images.githubusercontent.com/36611101/61166175-41bd2580-a55c-11e9-9757-bc15a992bcfa.png)

系统：[如Windows 10 1903]
程序版本：5.0.0.1

**Comment by HMBSbige** [comment]
这是[ssrr](https://github.com/shadowsocksrr/shadowsocksr-csharp)的协议吧，是有内存泄漏吗？

你还是到他们那边提 issue 吧
