### ISSUE TITLE
[BUG]不通过代理更新订阅时还是会走代理更新订阅

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#38]
5.0.0.0 BUG反馈：
1. 多订阅地址时，后面的订阅不生效。
2.不通过代理更新订阅信息时，还是会走代理更新订阅信息。而且我发现，如果当前所选择的节点服务器地址为 0.0.0.0 或者 0.0.0.1 这种不合法的IPv4时，会导致程序崩溃闪退
3.大量日志报错

场景：账号被封禁，此时，用户的订阅信息返回回来的是一个 服务器地址 为 0.0.0.0 或者 0.0.0.1 这种不合法的IPv4 (emm...我需要改进一下。。。)，当账号被恢复时，此时点击 “服务器订阅“-》“更新SSR服务器订阅（不通过代理）”，时，程序还是会使用当前节点去更新订阅信息，因为当前 节点服务器地址为 0.0.0.0 或 0.0.0.1 ，所以程序报异常，大量输出日志，并且崩溃闪退。

**Comment by ssrpanel** [comment]
【多订阅地址时，后面的订阅不生效。】

这个场景如下：
1.第一个订阅链接正常，并且手动输入过订阅连接的备注信息
2.第二个订阅连接录入后，没有填入备注信息
3.然后更新订阅连接，此时：第二个订阅连接的订阅信息并没有出现（订阅连接正常返回数据）

**Comment by HMBSbige** [comment]
暂时没法复现

新版订阅还有问题的话可以 Reopen，然后私聊我测试的订阅地址
