### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#4]
hi，大佬好
1.能否移除那个默认妹纸图
2.能否优化订阅（根据分组显示，而非统一取第一个ssr连接的分组名称）

**Comment by uloveme** [comment]
这么优秀的东西应用，现在敢维护的人都没有了

**Comment by Itzamana** [comment]
> 建议发给：https://github.com/shadowsocksrr/shadowsocksr-csharp
> 
> 我这里是兴趣使然的，有空才会去弄 :D
> 
> 1. 二维码生成这个比较容易弄
> 2. 因为我没有用过订阅，这个要弄可能有点困难


其实大佬可以考虑加上这个选项，有时还蛮好用的~

![pic](https://user-images.githubusercontent.com/9752596/49561625-1a401380-f910-11e8-93d9-2fd38fd31c4f.jpg)

**Comment by HMBSbige** [comment]
Update to 4.9.2

**Comment by ssrpanel** [comment]
@HMBSbige 感谢，东西特别棒
