### ISSUE TITLE
更新TLS1.3后生成解决方案为net472出错.

### ISSUE THREAD

**Issue by wxlg1117** [HMBSbige/ShadowsocksR-Windows#42]
生成解决方案过程出错:
`Program.cs(76,73,76,78): error CS0117: '“SecurityProtocolType”未包含“Tls13”的定义`
然后就失败了...

**Comment by HMBSbige** [comment]
因为 4.7.2 不支持 tls1.3 啊，早换成 4.8 的了

我记得生成脚本早换成 net48 啊
