### ISSUE TITLE
5.0.0.1版本无法修改ssr://链接

### ISSUE THREAD

**Issue by Recollections** [HMBSbige/ShadowsocksR-Windows#43]
如图，在编辑服务器时，该栏目为深灰色，只可复制不可粘贴。不勾选左侧“SSR链接”选项，效果也一样，无法修改。
![图片](https://user-images.githubusercontent.com/17669084/61621657-eb5f8d80-aca5-11e9-89ba-952f6ab0321e.png)

**Comment by HMBSbige** [comment]
就是不让粘帖啊？？？

你想导入的话右键通知栏的图标导入

**Comment by Recollections** [comment]
好的，因为历史版本这里是可以编辑的:)

**Comment by HMBSbige** [comment]
> 好的，因为历史版本这里是可以编辑的:)

什么版本啊，我的版本应该都是不可以的啊...
