### ISSUE TITLE
[BUG] ShadowsocksR.dll not exist

### ISSUE THREAD

**Issue by mengyan183** [HMBSbige/ShadowsocksR-Windows#44]
ShadowsocksR.dll not exist ; 
windows 10 打开 ssr 5.0.0 提示 the application to execute does not exist: ShadowsocksR.dll

**Comment by HMBSbige** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows/issues/40#issuecomment-514024284

**Comment by mengyan183** [comment]
ShadowsocksR-netcore-win64.zip 会出现这个问题 ; 切换为 ShadowsocksR-net48-5.0.0.1.zip 就 ok 了
