### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kesai** [HMBSbige/ShadowsocksR-Windows#46]
编辑服务器时,将服务列表全部删除时会报错,然后强制退出了

**Comment by HMBSbige** [comment]
无法复现...

**Comment by kesai** [comment]
> 无法复现...
> 
> 详细描述一下复现过程..

点击编辑服务器,弹出对话框里全选服务器列表,然后点击删除按钮会报错,虽然说必须保留一个服务器,但我觉得报错然后就退出程序还是处理一下好

**Comment by HMBSbige** [comment]
我这里没有报错...

空的列表再按删除才会报错退出，这个之后会修复

**Comment by kesai** [comment]
> 报错截图啊，我这里没有报错...
> 
> 空的列表再按删除才会报错退出，这个之后会修复

好的,就是那个错误
