### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BUG-P** [HMBSbige/ShadowsocksR-Windows#47]
**描述 bug**

无法打开v5.0.1.0版本。
Windows 10 1709 上-net48版，启动报错提示如下截图，-netcore版本未测试。
Win7 SP3 上双版本均启动失败无任何提示。

net48-5.0.0.1 版本在以上两个系统内均可正常运行。

**截图**

![Capture](https://user-images.githubusercontent.com/54699498/63995552-82342b00-cb2b-11e9-81c5-67687760abd4.jpg)

**环境**

 - 系统：Windows 10 1709，Win7 SP3
 
**其它内容**

日志内容同截图内容，Win7下并未生成temp文件夹，故无日志内容

**Comment by HMBSbige** [comment]
需要安装 .NET Framework 4.8
README 写了

**Comment by BUG-P** [comment]
安装[.NET Framework 4.8](https://dotnet.microsoft.com/download/thank-you/net48-offline) 后问题解决，谢谢回复。
