### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ssacpklnm** [HMBSbige/ShadowsocksR-Windows#48]
**描述 bug**

右键软件后，所有带小三角的二级菜单都无法选中

说明您在进行了怎样的操作后出现了bug：

1. 右键右下角任务栏
2. 将光标移动到有二级菜单的行，比如系统代理模式或PAC
3. 二级菜单出现
4.再将光标移动到二级菜单，比如我想选中系统代理模式的PAC模式，当我光标移出一级菜单的那一刻，二级菜单便消失了，导致无法选中二级选项
5.由此引起无法切换代理模式，无法切换服务器等等众多操作
6.可以用键盘方向键控制选中，但很麻烦

光标选中一级菜单
![image](https://user-images.githubusercontent.com/9998735/63996298-e6f08500-cb2d-11e9-9596-89a69e7e044a.png)

将光标左移，二级菜单消失，无法选中
![image](https://user-images.githubusercontent.com/9998735/63996337-fbcd1880-cb2d-11e9-8b99-b573d056ce4e.png)

**环境**

 - 系统：Windows 10 1903
 - 程序版本：ShadowsocksR-net48 v5.0.1.0

**Comment by HMBSbige** [comment]
仅当子菜单出现在左边时才会出现这个 bug，预计下个版本修复

**Comment by ssacpklnm** [comment]
> 仅当子菜单出现在左边时才会出现这个 bug，预计下个版本修复

除非将任务栏移到屏幕左侧，否则不能出现到右侧zzz

**Comment by HMBSbige** [comment]
> > 仅当子菜单出现在左边时才会出现这个 bug，预计下个版本修复
> 
> 除非将任务栏移到屏幕左侧，否则不能出现到右侧zzz

你也可以降低鼠标报告率23333

**Comment by ssacpklnm** [comment]
> > > 仅当子菜单出现在左边时才会出现这个 bug，预计下个版本修复
> > 
> > 
> > 除非将任务栏移到屏幕左侧，否则不能出现到右侧zzz
> 
> 你也可以降低鼠标报告率23333

好像。。。如果以极快的速度往左移倒是可以。。。哈哈，但还是希望尽快修复，谢谢
