### ISSUE TITLE
[BUG] 右击菜单，左侧出现的二级菜单移动光标过去有几率消失

### ISSUE THREAD

**Issue by lan542662** [HMBSbige/ShadowsocksR-Windows#49]
**描述 bug**

右击图标，一级目录弹出的二级内容，鼠标移过去，二级目录随机消失不见

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 右击图标
2. 鼠标放在有二级菜单的一级菜单中，二级菜单会出现，有时在左侧，有时在右侧
3. 从一级菜单移动到在左侧出现二级菜单，有很大几率二级菜单消失(右侧出现的二级菜单没问题)

**环境**

 - 系统：[如 Windows 10 1809]
 - 浏览器：[如 Chrome 76.0.3729.157，无关则删除]
 - 程序版本：[如 5.0.1.0 .Net Core SelfContained x64]

**Comment by HMBSbige** [comment]
#48

**Comment by bear7510** [comment]
我也这样，根本无法正常使用
