### ISSUE TITLE
全局模式下的流量疑问

### ISSUE THREAD

**Issue by wuzhushu** [HMBSbige/ShadowsocksR-Windows#5]
软件版本：ShadowsocksR-win-dotnet4.0-4.9.1.exe
疑问问题：系统代理模式修改为全局模式，代理规则修改为绕过局域网和大陆的设置下。在百度中查询ip，显示ip地址显示为国外vps服务器地址。
疑问原因：因为代理规则为绕过局域网和大陆。百度查询的ip不会显示为国外的vps，而是应该显示对应宽带国内的ip地址。

**Comment by wuzhushu** [comment]
是否全局模式下以及修改代理规则下，流量没有绕过局域网和大陆。导致百度查询IP的问题。
谢谢。

**Comment by HMBSbige** [comment]
绕过局域网和大陆需要根目录有 'chn_ip.txt'

不会自己生成的可以直接下载 https://raw.githubusercontent.com/HMBSbige/Text_Translation/master/ShadowsocksR/chn_ip.txt
