### ISSUE TITLE
[BUG]ShadowsocksR-net48-5.0.1.0最新版无法翻墙

### ISSUE THREAD

**Issue by kesai** [HMBSbige/ShadowsocksR-Windows#50]
国内网站在全局模式下都能打开,油管谷歌脸书都不行
错误日志:
[2019-08-30 14:37:14] ShadowsocksR started on port 1080
[2019-08-30 14:37:14] [Error] System.OverflowException: 算术运算导致溢出。
   在 Shadowsocks.Proxy.SystemProxy.SetSystemProxy.Initialize(INTERNET_PER_CONN_OPTION_LIST& options, ProxyType type, String url, String bypass)
   在 Shadowsocks.Proxy.SystemProxy.SetSystemProxy.Global(String url, String bypass)
   在 Shadowsocks.Proxy.SystemProxy.SystemProxy.Update(Configuration config, Boolean forceDisable, PACServer pacSrv)
[2019-08-30 14:37:24] [Info] Connect api.github.com:443 via 209.58.188.157:8099
[2019-08-30 14:37:24] [Info] DNS query api.github.com answer 13.250.94.254
[2019-08-30 14:37:24] [Info] DNS nolock query api.github.com answer 13.250.94.254
[2019-08-30 14:37:24] 
============================

**Comment by lan542662** [comment]
刚试了下，一样的错误内容，不能上。

**Comment by HMBSbige** [comment]
提供一下系统版本

**Comment by leewi9** [comment]
刚刚也满怀希望地下载了，也是无法FQ

系统是windows 10 pro 1903

**Comment by HMBSbige** [comment]
> 我刚调试了下,可能是64位机器的问题
> // copy the array over into that spot in memory ...
> for (var i = 0; i < perOption.Length; ++i)
> {
> var opt = new IntPtr(optionsPtr.ToInt64() + i * optSize);
> Marshal.StructureToPtr(perOption[i], opt, false);
> }
> 改成ToInt64可以,我的是win10 64位系统,不知道是不是这个原因

很可能，但是我也是Win10 1903 x64 却没有问题..

**Comment by kesai** [comment]
> > 我刚调试了下,可能是64位机器的问题
> > // copy the array over into that spot in memory ...
> > for (var i = 0; i < perOption.Length; ++i)
> > {
> > var opt = new IntPtr(optionsPtr.ToInt64() + i * optSize);
> > Marshal.StructureToPtr(perOption[i], opt, false);
> > }
> > 改成ToInt64可以,我的是win10 64位系统,不知道是不是这个原因
> 
> 很可能，但是我也是Win10 1903 x64 却没有问题..

我改成to64的确能FQ了呢

**Comment by lan542662** [comment]
> 提供一下系统版本
> 
> 是系统代理没设置上还是只有全局有问题？

就全局有问题windoews 10 64 1703，和楼主一样的错误。
