### ISSUE TITLE
[BUG]不支持请求的安全协议

### ISSUE THREAD

**Issue by Merlyx** [HMBSbige/ShadowsocksR-Windows#54]
**描述 bug**

启动失败 提示不支持请求的安全协议
回退前一版本正常

**环境**

 - 系统：Windows 10 LTSC 1809 X64
 - 程序版本：5.0.1.2
 
**日志**

[2019-08-30 18:18:42] [Error] System.NotSupportedException: 不支持请求的安全协议。
   在 System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
   在 Shadowsocks.Program.Main(String[] args)

**Comment by HMBSbige** [comment]
#47
