### ISSUE TITLE
[BUG]程序无法打开…

### ISSUE THREAD

**Issue by Itzamana** [HMBSbige/ShadowsocksR-Windows#55]
![QQ截图20190831031324.png](https://i.loli.net/2019/08/31/6HctNprEioubjgT.png)
https://i.loli.net/2019/08/31/6HctNprEioubjgT.png

5001一切正常，5010和5012都是这样…不知道为什么…

**Comment by HMBSbige** [comment]
确定安装了 .NET Framework 4.8？

**Comment by Brightmbsh** [comment]
> 确定安装了 .NET Framework 4.8？

确实是安装了的 我这边同样打不开 系统是64位Win10 1607
5001一切正常

**Comment by HMBSbige** [comment]
你们可以试试 net core 版的，需要安装 [sdk](https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-preview8-windows-x64-installer)

**Comment by HMBSbige** [comment]
> > 确定安装了 .NET Framework 4.8？
> 
> 确实是安装了的 我这边同样打不开 系统是64位Win10 1607
> 5001一切正常
> https://i.loli.net/2019/08/31/QBh3qpS5Eokenmc.png

你这要么是没装，要么就是可能存在旧版本，用旧版本运行了

**Comment by HMBSbige** [comment]
我编译上传了自带运行库的版本 [releases](https://github.com/HMBSbige/ShadowsocksR-Windows/releases)

**Comment by Brightmbsh** [comment]
多谢，这个虽然大了点，但是没问题

**Comment by HMBSbige** [comment]
我又重新打包了，我觉得就是同时存在旧版本的 .NET Framework 导致的错误

有问题的就重新下吧

**Comment by Itzamana** [comment]
> 我又重新打包了，我觉得就是同时存在旧版本的 .NET Framework 导致的错误
> 
> 有问题的就重新下吧

确实是这样的，旧版本.NET Framework导致的…感谢回复
