### ISSUE TITLE
建议：默认不显示二维码

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#57]
1.建议默认不显示二维码，越简洁越好；
2.SSR连接那个checkbox 不勾选时显示ssr连接但不显示二维码图，勾选时还是显示ssr连接并显示二维码图片（废弃ss:\\链接，这玩意还保留着貌似没啥意义）

**Comment by HMBSbige** [comment]
我加了个按钮，用于显示二维码，ss链接还是保留了
