### ISSUE TITLE
win10重启后会导致mt5无法连接服务器

### ISSUE THREAD

**Issue by keplerkepler** [HMBSbige/ShadowsocksR-Windows#6]
ShadowsocksR-win-dotnet4.0-4.9.1.exe
系统 windows10专业工作站版
无论是先修改为直接连接再右键推出还是直接重启
重启以后都会导致mt5交易软件无法连接服务器
今天我因此亏损超过3000USD，特地来告诉你一声。
@HMBSbige 学生就好好上学 别出来害人了。

**Comment by HMBSbige** [comment]
你有点搞笑
