### ISSUE TITLE
代理规则里绕过局域网和大陆选项无效

### ISSUE THREAD

**Issue by accxj** [HMBSbige/ShadowsocksR-Windows#60]
代理规则里绕过局域网和大陆选项无效。
绕过之后还是会通过代理访问大陆网站

**Comment by HMBSbige** [comment]
正确配置 chn_ip.txt 了吗

**Comment by accxj** [comment]
> 正确配置chn_ip.txt了吗

忘了忘了  不好意思

**Comment by ashkyrene** [comment]
怎么配置chn_ip.txt?不懂哎。

**Comment by accxj** [comment]
> 怎么配置chn_ip.txt？不懂哎。

https://github.com/HMBSbige/Text_Translation/raw/master/ShadowsocksR/chn_ip.txt
下载这个放到同目录下

**Comment by ashkyrene** [comment]
好的，好的，谢谢大佬！

accxj <notifications@github.com> 于2019年10月9日周三 下午6:12写道：
