### ISSUE TITLE
[BUG]在[服务器记录]页，点击[服务器]列或[开关]列后会导致服务器重新排列

### ISSUE THREAD

**Issue by northsheep** [HMBSbige/ShadowsocksR-Windows#61]
**描述 bug**

**服务器记录**页面中，在已按照其他列升序或降序排列好后，左键单击**服务器列**或**开关**列下任意格子（如**已启用** 或 **已禁用**）会让所有服务器重新按照**ID**列升序排列。

该bug（或者feature？但是破娃酱的版本没这个“feature”...）会让在禁用大量出错比例高的服务器时，需要在禁用其中一个服务器后重新按照**出错比例**排列，再禁用下一个，较为麻烦。

**如何复现**
1. 鼠标中键单击任务栏的ssr图标，打开**服务器记录**页面；
2. 鼠标左键双击**出错比例**这四个字；
3. 在**开关**列禁用出错比例最高的服务器；

**预期行为**
第3步之前，服务器按照出错比例降序排列；第3步之后，服务器重新按照ID升序排列。

**截图**
点击**已禁用**前：
![image](https://user-images.githubusercontent.com/13964012/64273731-840b4d80-cf74-11e9-976e-93ae50e0e8c9.png)

点击**已禁用**后：
![image](https://user-images.githubusercontent.com/13964012/64273875-caf94300-cf74-11e9-93e8-0fc4c9a24831.png)

**环境**

 - 系统： Windows 10 1903
 - 程序版本：v5.0.2.0 net48

**Comment by HMBSbige** [comment]
列表重载直接赋值导致的，改成 Clear 后一个一个加就可以了
