### ISSUE TITLE
能否对新增订阅添加唤起客户功能

### ISSUE THREAD

**Issue by cjiasu** [HMBSbige/ShadowsocksR-Windows#64]
类似IOS小火箭网页点击一键添加按钮自动唤起客户端添加订阅,按钮地址格式sub://aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0hNQlNiaWdlL1RleHRfVHJhbnNsYXRpb24vbWFzdGVyL1NoYWRvd3NvY2tzUi9mcmVlbm9kZXBsYWluLnR4dA

自带订阅节点可以删除吗好像没什么用？

**Comment by HMBSbige** [comment]
可以唤起啊，不就是 URL Scheme 吗？更新日志里写了

自带订阅节点是默认值，总要有默认值的

**Comment by cjiasu** [comment]
> 可以起起啊，不就是URL Scheme吗？更新日志里写了
> 
> 自带订阅节点是默认值，总要有默认值的

好像可以 版本有点多了 能不能加个32位系统和64位系统通用的

**Comment by HMBSbige** [comment]
> > 可以起起啊，不就是URL Scheme吗？更新日志里写了
> > 自带订阅节点是默认值，总要有默认值的
> 
> 好像可以 版本有点多了 能不能加个32位系统和64位系统通用的

4个版本有两个版本都是通用的...

**Comment by cjiasu** [comment]
> > > 可以起起啊，不就是URL Scheme吗？更新日志里写了
> > > 自带订阅节点是默认值，总要有默认值的
> > 
> > 
> > 好像可以版本有点多了能不能加个32位系统和64位系统通用的
> 
> 4个版本有两个版本都是通用的，真就不看说明呗
ShadowsocksR-netcore.zip这个我WIN7旗舰用不了

**Comment by HMBSbige** [comment]
求求你看 wiki 吧，要安装 SDK 的


不同版本的区别见 [Wiki](https://github.com/HMBSbige/ShadowsocksR-Windows/wiki/ShadowsocksR-Windows-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#artifacts)
