### ISSUE TITLE
[BUG]訂閲節點有重複，沒有去重

### ISSUE THREAD

**Issue by cjsvaxlp** [HMBSbige/ShadowsocksR-Windows#65]
**描述 bug**

简要描述所遇到的bug

**如何复现**

说明您在进行了怎样的操作后出现了bug：

1. 
2. 
3. 

**预期行为**

简要描述进行以上操作后预期的脚本行为

**截图**

如果可以，请添加屏幕截图以帮助解释您的问题

**环境**

 - 系统：[如 Windows 10 1809]
 - 浏览器：[如 Chrome 74.0.3729.157，无关则删除]
 - 程序版本：[如 5.0.0.0 .Net Core SelfContained x64]
 
**其它内容**

在此添加有关此问题的任何其它内容。
最好能贴上相关的日志

**Comment by HMBSbige** [comment]
？

**Comment by HMBSbige** [comment]
把之前版本的节点删了就行了
