### ISSUE TITLE
大佬？我就问一个这里绝对没有出现的问题吧，大佬 请问你这个怎么配置白名单模式 你的软件里面的pac里面的 更新为绕过大陆域名和ip是否就是白名单？ pac是否选择这个  更新为绕过大陆域名和ip  然后代理规则选择绕过局域网和大陆 就是这个软件的白名单模式？

### ISSUE THREAD

**Issue by Goog686ii** [HMBSbige/ShadowsocksR-Windows#66]
大佬 请问你这个怎么配置白名单模式 你的软件里面的pac里面的 更新为绕过大陆域名和ip是否就是白名单？ pac是否选择这个  更新为绕过大陆域名和ip  然后代理规则选择绕过局域网和大陆 就是这个软件的白名单模式？

**Comment by anticpc** [comment]
> 大佬 请问你这个怎么配置白名单模式 你的软件里面的pac里面的 更新为绕过大陆域名和ip是否就是白名单？ pac是否选择这个 更新为绕过大陆域名和ip 然后代理规则选择绕过局域网和大陆 就是这个软件的白名单模式？

PAC模式已被 ''全局+代理规则(绕过局域网和大陆)'' 完全替代。

**Comment by HMBSbige** [comment]
1. PAC 绕过大陆域名和ip + 代理规则全局
2. 全局+ 代理规则绕过局域网和大陆
当然你也可以
3. PAC 绕过大陆域名和ip + 代理规则绕过局域网和大陆

注意使用代理规则最好要无污染的 DNS，有些 DNS 会把国内网站解析到 127.0.0.1 之类的本地地址

[wiki 传送门](https://github.com/HMBSbige/ShadowsocksR-Windows/wiki/system-mode-&-proxy-rule)

**Comment by Goog686ii** [comment]
好的 感谢，那 PAC绕过大陆域名和ip +代理规则全局 就是大陆白名单模式的意思吗，因为我只想使用PAC白名单模式  就是访问国内网站直连不走代理，访问海外网站一律全部走代理。这样就非常方便。

**Comment by HMBSbige** [comment]
> 好的 感谢，那 PAC绕过大陆域名和ip +代理规则全局 就是大陆白名单模式的意思吗，因为我只想使用PAC白名单模式 就是访问国内网站直连不走代理，访问海外网站一律全部走代理。这样就非常方便。

只是访问网站就用 PAC 吧，比代理规则快

**Comment by anticpc** [comment]
![image](https://user-images.githubusercontent.com/32192140/64589566-f9917680-d3d7-11e9-8c6b-ec63c96d8ebf.png)

**Comment by anticpc** [comment]
> > 好的 感谢，那 PAC绕过大陆域名和ip +代理规则全局 就是大陆白名单模式的意思吗，因为我只想使用PAC白名单模式 就是访问国内网站直连不走代理，访问海外网站一律全部走代理。这样就非常方便。
> 
> 只是访问网站就用 PAC 吧，比代理规则快

pac(绕过大陆域名和ip) + 代理规则是否理论上速度更快

**Comment by HMBSbige** [comment]
> > > 好的 感谢，那 PAC绕过大陆域名和ip +代理规则全局 就是大陆白名单模式的意思吗，因为我只想使用PAC白名单模式 就是访问国内网站直连不走代理，访问海外网站一律全部走代理。这样就非常方便。
> > 
> > 
> > 只是访问网站就用 PAC 吧，比代理规则快
> 
> pac(绕过大陆域名和ip) + 代理规则是否理论上速度更快

肯定比pac+全局慢啊，PAC判断一次，代理规则还要判断一次

pac相当于浏览器管的，代理规则是软件管的。顺便说一下白名单的 pac 已经大到不支持 firefox 了

代理规则的效率很慢的，条数大概5万条朝上时，就慢到浏览器等不急代理响应，全部默认直连了
