### ISSUE TITLE
[BUG]无法正常使用代理规则里的“绕过局域网和大陆”功能

### ISSUE THREAD

**Issue by fenglipop29** [HMBSbige/ShadowsocksR-Windows#67]
**描述 bug**

原先破娃酱的ssr在系统代理模式点“全局模式”，然后在代理规则里点“绕过局域网和大陆”，这个时候ssr就能自动地转换为外国ip全部用节点流量上网，本国流量不用节点。

但是在本ssr里面，使用同样的步骤，却无法正常转换过去，会变成全部流量都走节点流量上网。
我用百度查了下自己的ip地址，同样的步骤在破娃酱的ssr里面，百度下来的ip是自己的真实国内ip，但在本ssr里面用同样的步骤，百度下来的ip是节点的ip。
等于说这个“代理规则”不起作用。

**环境**

 - 系统：[ Windows 10 1903]
 - 浏览器：[ Chrome]
 - 程序版本：[ 5.1.0.1 ]

**Comment by HMBSbige** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows/issues/60#issuecomment-527823232
