### ISSUE TITLE
自定义规则中的问题

### ISSUE THREAD

**Issue by lan542662** [HMBSbige/ShadowsocksR-Windows#7]
在自定义中加入.qq.com 当然里面有cn ip段的内容。都是localproxy。但是QQ的公告和群文件内容是打不开
这是测试内容 ：加了.qq.com 域名的https://pastebin.com/EB8uh0ey
这是不加.qq.com localproxy域名的https://pastebin.com/7a2gchfR
另外就是局域网在规则中不能访问。绕过局域网不起作用。。安卓手机的acl却没有以上任何问题，局域网也正常。谢谢

**Comment by HMBSbige** [comment]
测试内容时 系统代理模式、PAC、代理规则分别选择了什么

**Comment by lan542662** [comment]
系统是全局模式，规则是自定义(GFWLIST remoteproxy 和国内域名 localproxy和china ip段localproxy
和 局域网ip direct)。
这样其实就是qq里才发现问题的，另外就是局域网设置打印机不能网页打开(需要在系统里排出打印机地址，PAC模式就没有这个问题，我想局域网属于PAC级别的，规则不起作用)
看了下其实qq也是直连的，不过日志中他是拒绝的。我想会不会是全局下的域名规则有些小问题。 .qq.com 并没有起到应有的作用，谢谢。

Bruce Wayne <notifications@github.com> 于2019年2月22日周五 下午11:43写道：

**Comment by HMBSbige** [comment]
- 全局+代理规则自定义如果规则列表太大的话，会出现响应时间过长
- 国内域名 localproxy，如果你设的全局，相当于国内域名走ssr，china ip段同理
- 所以你的全局+自定义规则相当于除了局域网直连，其他全走ssr
- 局域网不是很清楚，不知道你的打印机网页是域名还是 IP

https://github.com/HMBSbige/shadowsocks-rss/wiki/C%23-Proxy-Rule

**Comment by lan542662** [comment]
+ 我的列表11300多行，我精简过了。
+ 全局里也有规则，localproxy不是remoteproxy
+ 同上，全局规则不是全局远程代理
+ 设置是ip,但是网关是可以正常设置的。

Bruce Wayne <notifications@github.com> 于2019年2月23日周六 下午2:26写道：

**Comment by lan542662** [comment]
看日志，其实qq没有代理啊。另外我所有的分流都很正常的。现在是添加了.qq.com
<http://xn--ykqu3hoxexvtfgjnsi.qq.com>
localproxy，但是就是群文件和公告打不开而已。去掉的话靠ip段localproxy，就能打开了。我想是否对域名还设计qq其他一些东西。
局域网打印机是192.168.3.8，全局是打不开的，非要直连或者pac这样的级别才够。

Bruce Wayne <notifications@github.com> 于2019年2月23日周六 下午2:26写道：

**Comment by HMBSbige** [comment]
你是 全局+代理规则，localproxy的话就是走代理的，求你看看上面的wiki链接
`localproxy： 经过本地代理连接，或没有配置本地代理时使用直连连接`

**Comment by HMBSbige** [comment]
打印机我不知道什么情况，日志里也没出现，我这里也无法复现
我这里全局+绕过局域网，打印机不管网页还是打印都很正常

**Comment by HMBSbige** [comment]
还有也不知道你QQ的代理是怎么设置的

**Comment by lan542662** [comment]
我qq没有在客户端设置代理，另外尝试设置了代理，结果一样。你好奇的话也可以在规则里加个qq域名，然后用全局代理。仍然非常谢谢你的解答，我也是把wiki看了，然后自己做了很多次尝试，然后才发现问题在这的。想不明白，不过有个人和我说可能是源码的机制改了。我的是4.9.1版本

Bruce Wayne <notifications@github.com> 于 2019年2月23日周六 17:29写道：

**Comment by HMBSbige** [comment]
我当然试过了，但问题无法复现

代码也没改

还是要提醒你，如果你设的全局，自定义规则里的 localproxy 就相当于 remoteproxy

**Comment by lan542662** [comment]
我是全局，但是ip111测试下来，国内是国内，国外和谷歌是另外的ip。 按你所说，localproxy 好remoteproxy一样的话，检测下来应该是3个一样的ip。可是分的很清楚。
