### ISSUE TITLE
[BUG] 一个小bug…

### ISSUE THREAD

**Issue by Itzamana** [HMBSbige/ShadowsocksR-Windows#70]
代理模式为全局-绕过局域网和大陆，退出软件后会自动勾选“自动检测设置”，如图…

![1.jpg](https://i.loli.net/2019/09/14/j4XvZWeIk2FYDnd.jpg)

启动软件前和软件运行时这个都是没有勾选的…

**Comment by HMBSbige** [comment]
就是这样设计的，会有什么影响吗？

**Comment by Itzamana** [comment]
基本没啥影响，所以说是小bug嘛…

**Comment by Itzamana** [comment]
…总觉得加上自动检测原有设置，退出软件后恢复原设置会更好…

**Comment by Itzamana** [comment]
> 就是这样设计的，会有什么影响吗？

总感觉加上自动检测原有设置，退出软件后恢复原设置会更好…
