### ISSUE TITLE
[BUG]中文

### ISSUE THREAD

**Issue by MariostinMa** [HMBSbige/ShadowsocksR-Windows#71]
之前使用5.0之前的版本 在繁體中文下有中文，可是最新的v5.1.0.1沒有文中了

後續是否會加入中文

**Comment by HMBSbige** [comment]
繁中环境下显示全是英文？

**Comment by alfredDAI** [comment]
只有Global setting、Port setting、show logs...、的下級菜單才會有中文

**Comment by HMBSbige** [comment]
> 只有Global setting、Port setting、show logs...、的下級菜單才會有中文

你的区域设置是什么？因为正在改，有些只支持zh-TW

**Comment by alfredDAI** [comment]
您好，只有Global setting、Port setting、show logs...、的下級菜單才會有中文 ，其他都是英文。
謝謝！
[image: image.png]



Bruce Wayne <notifications@github.com> 於 2019年9月18日週三 上午11:36寫道：

**Comment by alfredDAI** [comment]
目前地區格式選擇的：中文（繁體、香港特別行政區）
國家和地區選擇：香港特別行政區

版本windows 10 專業版
版本：1903

Alfred Dai <minyu.d@gmail.com> 於 2019年9月18日週三 下午1:03寫道：

**Comment by HMBSbige** [comment]
如果有人能贡献翻译就好了，我记得台湾和香港有些用词术语不一样。之后版本我会暂时把两个繁中用同一个文件
