### ISSUE TITLE
[BUG] 运行出现Unexpected Error

### ISSUE THREAD

**Issue by anticpc** [HMBSbige/ShadowsocksR-Windows#73]
**截图**
![a](https://user-images.githubusercontent.com/32192140/65377101-6d862580-dcda-11e9-97db-ceabb3df0404.png)

**环境**
 - 地点：网吧
 - 系统：Windows 7 SP1
 - 程序版本：[v5.1.0.1 netcore win64]
 
**注明**
a. 因为使用地点在网吧，所以可能原因为缺少某些依赖文件? 但是运行Akkariiin的ssrr4.9.2 dotnet4.0 是没有问题的。
b. 之前在另一家网吧使用没有任何问题

Cheers.

**Comment by anticpc** [comment]
@HMBSbige  感谢对ssr项目的贡献

**Comment by HMBSbige** [comment]
首先如果使用netcore64这种带运行库版本都抛出这种缺运行库的操作，明显是系统问题

网吧系统可能无盘，无法释放运行库

系统环境问题最好进tg问，这里仅接受软件bug反馈

**Comment by anticpc** [comment]
> 首先如果使用netcore64这种带运行库版本都抛出这种缺运行库的操作，明显是系统问题
> 
> 网吧系统可能无盘，无法释放运行库
> 
> 系统环境问题最好进tg问，这里仅接受软件bug反馈

请问你有自己的项目tg群吗，给个link

**Comment by HMBSbige** [comment]
看readme啊...

**Comment by anticpc** [comment]
> 看readme啊...

![image](https://user-images.githubusercontent.com/32192140/65430996-5adf2e00-de4b-11e9-80c0-e2243aec7b73.png)

家用电脑也突然出现了类似报错，原因不明。

通过删除temp文件夹后再运行clean.cmd命令后，已解决。

**Comment by HMBSbige** [comment]
> > 看readme啊...
> 
> ![image](https://user-images.githubusercontent.com/32192140/65430996-5adf2e00-de4b-11e9-80c0-e2243aec7b73.png)
> 
> 家用电脑也突然出现了类似报错，原因不明。
> 
> 通过删除temp文件夹后再运行clean.cmd命令后，已解决。

系统更新、奇奇怪怪的清理软件都可能导致运行库被删除...
