### ISSUE TITLE
[BUG]选择服务器有轻微卡顿

### ISSUE THREAD

**Issue by haley924** [HMBSbige/ShadowsocksR-Windows#76]
**描述 bug**

简要描述所遇到的bug

说明您在进行了怎样的操作后出现了bug：

1. 刚下载新版本，更新后发现ctrl+鼠标左键 点出来的节点列表，更换不同节点时会有两到三秒的卡顿

**环境**

 - 系统：[Windows 10 1903]
 
- 程序版本：[v5.1.1 net48]

**Comment by roshad** [comment]
为什么我一直不知道c.+左可以点出路由表
