### ISSUE TITLE
[BUG]全局模式下，选择绕过局域网和大陆，并没有绕过

### ISSUE THREAD

**Issue by uoox** [HMBSbige/ShadowsocksR-Windows#77]
全局模式下，选择绕过局域网和大陆，并没有绕过。

可在
http://ip111.cn/
验证

**Comment by HMBSbige** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows/issues/60#issuecomment-527823232

**Comment by HMBSbige** [comment]
顺便说下你发的这个网站返回的ip没一个真实的，还是有点问题的
