### ISSUE TITLE
PAC模式下pacjsworker进程大量出现

### ISSUE THREAD

**Issue by CJieLuo** [HMBSbige/ShadowsocksR-Windows#8]
Windows10 1809
无法结束进程
![a6b6c5ab-d4de-4376-af7d-1075498ce7a9 png](https://user-images.githubusercontent.com/22096448/53343349-281f9680-394b-11e9-8383-e0785a6fa8f4.jpg)
谷歌以后看到这里有一个解决方案：
https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/
应该是通病

**Comment by HMBSbige** [comment]
很早就发现，应该是微软的锅，想等微软修复的，我没感觉到什么影响

想要结束进程其实很简单，只要找到并杀死主进程就行了

![](https://user-images.githubusercontent.com/19153265/53344379-864d7900-394d-11e9-8616-cc54404db6ba.png)

最近没什么时间，欢迎 PR

~~等1903出来还有问题再解决~~

**Comment by HMBSbige** [comment]
Win10 1903 已修复

确定为 1809 的 bug
