### ISSUE TITLE
[改进建议]建议增加一个日志停止选项

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#82]
![微信图片_20190925233444.png](https://i.loli.net/2019/09/25/Q6kbxwrqfEAa1S9.png)

1.新下载的5.1.2（包括以前旧版），刚打开的时候疯狂刷新日志
2.当连接错误的时候，希望能复制黏贴日志，但是刷新的太快了，复制都来不及，如果有个开关勾选能临时停止刷日志就行了

**Comment by HMBSbige** [comment]
就是暂停滚动吧
