### ISSUE TITLE
建议增加一个不使用代理更新订阅的功能

### ISSUE THREAD

**Issue by VeTsgG** [HMBSbige/ShadowsocksR-Windows#84]
以便在节点失效时还能更新订阅

**Comment by HMBSbige** [comment]
@VeTsgG 二合一了，没必要再加回去

**Comment by VeTsgG** [comment]
为什么在使用失效节点时无法更新订阅

**Comment by ConnectionRefused** [comment]
@VeTsgG 使用的是最新版本嘛？ @HMBSbige 说他自己测的时候没有这个问题的

**Comment by ConnectionRefused** [comment]
@VeTsgG [回复 ネーム レス]
现在是，自动的，优先代理，如果代理不行，再直连的

**Comment by VeTsgG** [comment]
@ConnectionRefused 5.1.2.0 net48

**Comment by HMBSbige** [comment]
@VeTsgG 关闭代理，用浏览器访问订阅地址能不能正确获取订阅

**Comment by VeTsgG** [comment]
@HMBSbige 可以的 会下载一个txt

**Comment by HMBSbige** [comment]
@VeTsgG 试试 https://ci.appveyor.com/api/buildjobs/ayawx3jkq7sprtfw/artifacts/ShadowsocksR-net48.zip
再不行就是个人问题了...
