### ISSUE TITLE
[BUG]离奇的服务器记录窗口渲染 bug

### ISSUE THREAD

**Issue by Crystal-RainSlide** [HMBSbige/ShadowsocksR-Windows#86]
**描述 bug**

同组内，被更新节点左侧出现空白，鼠标悬浮时会高亮。被更新节点都已启用。未被更新节点已禁用。
![图片](https://user-images.githubusercontent.com/16851802/65832299-4c35c280-e2f4-11e9-8392-03448c79805e.png)

**如何复现**
打开该窗口，通过托盘菜单更新节点。

**环境**

 - 系统：Windows 10 默认更新频道最新
 - 程序版本：5.1.2 最新
 
**其它内容**

可能要徒手整一个订阅源来调试和复现，比较麻烦，同时影响也不算大，不方便的话就搁着吧

**Comment by HMBSbige** [comment]
电脑太卡导致的。

既然那么多人说卡，那么下版本就把分组去掉...

**Comment by Crystal-RainSlide** [comment]
成吧，自己排一下顺序，也就很好了
