### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by anye1998** [HMBSbige/ShadowsocksR-Windows#87]
希望什么时候添加如图那个功能，节点故障可以自动切换。毕竟负载均衡看视频有时候加载实在捉急。
![Snipaste_2019-10-02_16-05-58](https://user-images.githubusercontent.com/43033792/66028267-4f68c280-e52f-11e9-8567-220a40113906.png)

**Comment by HMBSbige** [comment]
跟 自动禁用出错服务器 功能重复
