### ISSUE TITLE
[功能建议] 能否考虑增加快捷键功能？

### ISSUE THREAD

**Issue by reaCodes** [HMBSbige/ShadowsocksR-Windows#88]
类似Shadowsocks-windows的快捷键，经常使用的几个功能，如果可以设置自定义全局快捷键，那将非常方便

例如：
1、切换系统代理模式（PAC - 全局）
2、显示日志
3、显示服务器连接统计
4、编辑服务器

我觉得这几个都是大部分用户经常使用的功能，应该有快捷键

------
感谢作者的劳动成果！

**Comment by HMBSbige** [comment]
#45

**Comment by reaCodes** [comment]
我觉得`ShadowsocksR-windows`各个方面都比`Shadowsocks-windows`好，尤其作者这个版本解决了高分屏的支持问题，UI很漂亮，但是就是没有快捷键，任何小的操作都要动鼠标去找设置的地方，便捷度不如`Shadowsocks-windows`

**Comment by HMBSbige** [comment]
> 我觉得`ShadowsocksR-windows`各个方面都比`Shadowsocks-windows`好，尤其作者这个版本解决了高分屏的支持问题，UI很漂亮，但是就是没有快捷键，任何小的操作都要动鼠标去找设置的地方，便捷度不如`Shadowsocks-windows`

Issue 重复了...
