### ISSUE TITLE
[BUG]服務器記錄界面BUG已修復，服務器編輯界面顯示BUG還有

### ISSUE THREAD

**Issue by kkbbzjh** [HMBSbige/ShadowsocksR-Windows#92]
服務器記錄界面BUG已修復，服務器編輯界面顯示BUG還有，服務器編輯界面的左邊服務器列表，鼠標一掃，爆BUG，謝謝大佬修復
![image](https://user-images.githubusercontent.com/17746225/66323696-c3073700-e956-11e9-8f60-bc3de6e2464c.png)

**Comment by HMBSbige** [comment]
@kkbbzjh 猜测是显卡问题，重装显卡驱动试试？

**Comment by kkbbzjh** [comment]
哦哦？這樣？我的2080是不是有點，不兼容？

**Comment by HMBSbige** [comment]
我先关闭了，这应该是个人问题

PS: 可以进 Tg 群询问，看看有没有大佬知道

**Comment by kkbbzjh** [comment]
好的，诶诶诶~~~TG群呢？？？？

**Comment by HMBSbige** [comment]
@kkbbzjh ¿ 下载时不看上面简介
