### ISSUE TITLE
建议添加“删除服务器分组”功能

### ISSUE THREAD

**Issue by qazmko1029** [HMBSbige/ShadowsocksR-Windows#93]
如题，具体想要的效果就是在“编辑服务器”窗口里左侧列表选中分组的时候，右侧窗口添加个删除分组和里面全部服务器项目的按钮。
主要是在服务器订阅更新的时候，旧的内容不会自动删除，这点会有点麻烦。

PS: 5.1.3.2版已捐助 2019/10/8

**Comment by HMBSbige** [comment]
¿没看懂

要删除分组的话，左边 TreeView 不是可以的吗？

订阅更新时已经下线的节点一直都会自动删除啊

**Comment by qazmko1029** [comment]
好吧，是我之前一直不知道这列表还能右键……姑且是可以在选中分组的右侧加几个按钮或者加一行提示，打扰了
