### ISSUE TITLE
最新代码编译后每次启动运行后第一次点击服务器管理或者服务器记录后会弹窗Syncfusion License...

### ISSUE THREAD

**Issue by wxlg1117** [HMBSbige/ShadowsocksR-Windows#94]
![Snipaste_2019-10-08_11-36-25](https://user-images.githubusercontent.com/9752596/66449178-b3870b80-ea86-11e9-949e-a948ddec3074.png)

有大佬说下是需要安装啥东东么?

另外每次启动运行后第一次点击服务器记录后的弹窗先显示为竖的长条然后再扩展为正常显示...是正常的么?

**Comment by HMBSbige** [comment]
@wxlg1117 需要 Syncfusion 的 license，自己想办法去搞

**Comment by wxlg1117** [comment]
搞了试用key,安装了syncfusionessentialwpf_trial.exe,运行了Syncfusion WPF Control Panel的toolbox installer的install vs2019>>>Perform Action,但是看VS好像还是调用nuget的C:\Users\Administrator\.nuget\packages\syncfusion.sfgrid.wpf\17.3.0.14...
求问大佬怎么搞起?

**Comment by HMBSbige** [comment]
@wxlg1117 仔细熟读官方文档

有开发问题还是进tg群来问
