### ISSUE TITLE
更新订阅失败

### ISSUE THREAD

**Issue by bingotl** [HMBSbige/ShadowsocksR-Windows#96]
第一次打开小飞机，填入订阅地址，保存更新，发觉一直更新失败。研究了好久才发现要把代理规则设置为“绕过局域网和非大陆”，并且只有这个选项才能更新订阅，但是我们正常使用极少数情况才选这个规则的，所以更新完订阅又要切换回来。

希望所有更新订阅都默认不通过代理，因为假如节点被墙了，那么就导致无法更新订阅，然后又要设置一次这个规则，才能更新订阅

另外有个小小小小的建议，为什么安卓和win都要保留那个FreeSSR-Public的默认配置啊，每次都要删除掉，不删除还会影响更新订阅的速度。对老手来说不是什么问题，但是对于要写图文教程给小白看的话，就是多了一个步骤了。

**Comment by HMBSbige** [comment]
@bingotl 无法复现操作

我这里都能成功更新，成功更新后自动就删除默认的服务器了

你确定订阅地址国内能流畅访问？

**Comment by bingotl** [comment]
因为机场的订阅链接是国外服务器的，第一次设置小飞机，我试了只有“绕过局域网和非大陆”才能更新订阅，其他都更新失败

**Comment by bingotl** [comment]
当代理能正常使用的时候选哪个都没问题，但是当节点不能用，或者当第一次设置小飞机，只有选“绕过局域网和非大陆”才能更新（订阅链接是国外ip）

**Comment by HMBSbige** [comment]
@bingotl 我就拿默认订阅地址测试的，马上就更新成功了

机场主建议私聊定制

**Comment by bingotl** [comment]
好吧，我试了个其他机场确实没问题，先close
