### ISSUE TITLE
可以添加几个功能吗

### ISSUE THREAD

**Issue by yuningning520** [HMBSbige/ShadowsocksR-Windows#97]
删除重复节点  在通过很多渠道收集的节点经常会有重复的
在 服务器连接统计 里，操作里加入 负载均衡 开关或者延迟测试也可以，另外添加直接删除节点，不能使用的节点要对照服务器编辑删不是很方便
可以参考下隔壁v2rayN界面的源码

**Comment by HMBSbige** [comment]
加钱可以做
