### ISSUE TITLE
菜单简洁化设计

### ISSUE THREAD

**Issue by ssrpanel** [HMBSbige/ShadowsocksR-Windows#99]
1.这是改进优化性建议
理由：目前的客户端已经很完美，美中不足的是客户的菜单不够简洁，针对普通用户给了太多的选择，建议简化菜单（非简化功能）

代理模式
      ----| 直连
      ----| PAC
      ----| 全局
      -------------------
      ----| 保持当前状态不变
规则设置
      ----| PAC设置 （即现有一级菜单：PAC）
      ----| 规则设置 （即现有一级菜单：代理规则）
服务器
       ----|  服务器列表
       ----|  编辑服务器
       -------------------
       ----|  扫描二维码
       ----|  从链接导入
       ----|  从文件导入
       -------------------
       ----|  负载均衡
       ----|  同址优先  （现有的： 优先相同节点连接同一个地址）
       -------------------
       ----|  连接统计
       ----|  强制断开连接
订阅
       ----| 设置 
       ----| 更新
日志
更多 （现有的： 帮助）
       ----| 选项设置
       ----| 端口设置
       ----| 其他菜单
       -------------------
       ----| 帮助文档 （跳github的wiki）
       ----| 问题反馈 （跳github的issues）
       ----| 打赏作者
       -------------------
       ----| 设置客户端密码 （移除掉：自定义生成二维码，这个功能是鸡肋）
       ----| 更新 （移除掉：关于，上面有帮助文档和问题反馈了）
退出

**Comment by ssrpanel** [comment]
望采纳

**Comment by wxlg1117** [comment]
现有的： 优先相同节点连接同一个地址

优先使用同一节点连接同一域名系列地址;


因为输入的地址属于和之前某些处于正打开状态的页面为同一域地址,那就继续使用负载均衡节点列表里之前用于打开页面的节点再次打开页面...

所以这里应该缩写为<同节点优先>吧?

**Comment by HMBSbige** [comment]
> 现有的： 优先相同节点连接同一个地址
> 
> 优先使用同一节点连接同一域名系列地址;
> 
> 因为输入的地址属于和之前某些处于正打开状态的页面为同一域地址,那就继续使用负载均衡节点列表里之前用于打开页面的节点再次打开页面...
> 
> 所以这里应该缩写为<同节点优先>吧?

感觉不是很好

**Comment by anticpc** [comment]
··· 刚用上新版本，沃日  菜单现在好简洁

**Comment by yongfrank** [comment]
不是很理解同址優先的意思，希望能夠解釋一下。

**Comment by da-montagne** [comment]
请教下 同址优先和负载均衡可以一起使用吗

**Comment by yfdyh000** [comment]
@yongfrank 现存在与[x]域名的连接时，后续连接该域名则优先选用已连该域名的服务器节点。
@da-montagne 可以，应该是同址优先。

**Comment by wxlg1117** [comment]
> 
> 
> 请教下 同址优先和负载均衡可以一起使用吗

同址优先应该是负载均衡功能下的一个子选项:只有在负载均衡启用的情况下勾选同址优先后才有效果,负载均衡不启用的情况下同址优先就算勾选也应该是无效的

**Comment by da-montagne** [comment]
@wxlg1117 @yfdyh000 了解,感谢两位大佬.
